import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('country_history').del();
  await knex('country_geography').del();
  await knex('countries').del();

  const countries = await knex('countries')
    .insert([
      {
        name: 'France',
        official_name: 'République française',
        code_iso2: 'FR',
        code_iso3: 'FRA',
        capital: 'Paris',
        region: 'Europe',
        subregion: 'Europe de l\'Ouest',
        continent: 'Europe',
        population: 67390000,
        area_km2: 551695,
        languages: JSON.stringify({ fr: 'Français' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/fr.png',
        latitude: 46.2276,
        longitude: 2.2137,
        borders: JSON.stringify(['BEL', 'LUX', 'DEU', 'CHE', 'ITA', 'ESP', 'AND', 'MCO']),
        timezones: JSON.stringify(['Europe/Paris']),
      },
      {
        name: 'Allemagne',
        official_name: 'République fédérale d\'Allemagne',
        code_iso2: 'DE',
        code_iso3: 'DEU',
        capital: 'Berlin',
        region: 'Europe',
        subregion: 'Europe de l\'Ouest',
        continent: 'Europe',
        population: 83240000,
        area_km2: 357114,
        languages: JSON.stringify({ de: 'Allemand' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/de.png',
        latitude: 51.1657,
        longitude: 10.4515,
        borders: JSON.stringify(['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NLD', 'POL', 'CHE']),
        timezones: JSON.stringify(['Europe/Berlin']),
      },
      {
        name: 'Italie',
        official_name: 'République italienne',
        code_iso2: 'IT',
        code_iso3: 'ITA',
        capital: 'Rome',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 60360000,
        area_km2: 301340,
        languages: JSON.stringify({ it: 'Italien' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/it.png',
        latitude: 41.8719,
        longitude: 12.5674,
        borders: JSON.stringify(['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT']),
        timezones: JSON.stringify(['Europe/Rome']),
      },
      {
        name: 'Royaume-Uni',
        official_name: 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord',
        code_iso2: 'GB',
        code_iso3: 'GBR',
        capital: 'Londres',
        region: 'Europe',
        subregion: 'Europe du Nord',
        continent: 'Europe',
        population: 67886000,
        area_km2: 242495,
        languages: JSON.stringify({ en: 'Anglais' }),
        currencies: JSON.stringify({ GBP: { name: 'Livre sterling', symbol: '£' } }),
        flag_url: 'https://flagcdn.com/w320/gb.png',
        latitude: 55.3781,
        longitude: -3.4360,
        borders: JSON.stringify(['IRL']),
        timezones: JSON.stringify(['Europe/London']),
      },
      {
        name: 'Espagne',
        official_name: 'Royaume d\'Espagne',
        code_iso2: 'ES',
        code_iso3: 'ESP',
        capital: 'Madrid',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 47350000,
        area_km2: 505992,
        languages: JSON.stringify({ es: 'Espagnol' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/es.png',
        latitude: 40.4637,
        longitude: -3.7492,
        borders: JSON.stringify(['AND', 'FRA', 'GIB', 'PRT', 'MAR']),
        timezones: JSON.stringify(['Europe/Madrid']),
      },
      {
        name: 'États-Unis',
        official_name: 'États-Unis d\'Amérique',
        code_iso2: 'US',
        code_iso3: 'USA',
        capital: 'Washington, D.C.',
        region: 'Amérique',
        subregion: 'Amérique du Nord',
        continent: 'Amérique du Nord',
        population: 331900000,
        area_km2: 9833520,
        languages: JSON.stringify({ en: 'Anglais' }),
        currencies: JSON.stringify({ USD: { name: 'Dollar américain', symbol: '$' } }),
        flag_url: 'https://flagcdn.com/w320/us.png',
        latitude: 37.0902,
        longitude: -95.7129,
        borders: JSON.stringify(['CAN', 'MEX']),
        timezones: JSON.stringify(['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles']),
      },
      {
        name: 'Japon',
        official_name: 'Japon',
        code_iso2: 'JP',
        code_iso3: 'JPN',
        capital: 'Tokyo',
        region: 'Asie',
        subregion: 'Asie de l\'Est',
        continent: 'Asie',
        population: 125800000,
        area_km2: 377975,
        languages: JSON.stringify({ ja: 'Japonais' }),
        currencies: JSON.stringify({ JPY: { name: 'Yen', symbol: '¥' } }),
        flag_url: 'https://flagcdn.com/w320/jp.png',
        latitude: 36.2048,
        longitude: 138.2529,
        borders: JSON.stringify([]),
        timezones: JSON.stringify(['Asia/Tokyo']),
      },
      {
        name: 'Égypte',
        official_name: 'République arabe d\'Égypte',
        code_iso2: 'EG',
        code_iso3: 'EGY',
        capital: 'Le Caire',
        region: 'Afrique',
        subregion: 'Afrique du Nord',
        continent: 'Afrique',
        population: 102300000,
        area_km2: 1002450,
        languages: JSON.stringify({ ar: 'Arabe' }),
        currencies: JSON.stringify({ EGP: { name: 'Livre égyptienne', symbol: '£' } }),
        flag_url: 'https://flagcdn.com/w320/eg.png',
        latitude: 26.8206,
        longitude: 30.8025,
        borders: JSON.stringify(['ISR', 'LBY', 'PSE', 'SDN']),
        timezones: JSON.stringify(['Africa/Cairo']),
      },
      {
        name: 'Grèce',
        official_name: 'République hellénique',
        code_iso2: 'GR',
        code_iso3: 'GRC',
        capital: 'Athènes',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 10720000,
        area_km2: 131957,
        languages: JSON.stringify({ el: 'Grec' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/gr.png',
        latitude: 39.0742,
        longitude: 21.8243,
        borders: JSON.stringify(['ALB', 'BGR', 'TUR', 'MKD']),
        timezones: JSON.stringify(['Europe/Athens']),
      },
      {
        name: 'Chine',
        official_name: 'République populaire de Chine',
        code_iso2: 'CN',
        code_iso3: 'CHN',
        capital: 'Pékin',
        region: 'Asie',
        subregion: 'Asie de l\'Est',
        continent: 'Asie',
        population: 1412000000,
        area_km2: 9596961,
        languages: JSON.stringify({ zh: 'Chinois mandarin' }),
        currencies: JSON.stringify({ CNY: { name: 'Yuan', symbol: '¥' } }),
        flag_url: 'https://flagcdn.com/w320/cn.png',
        latitude: 35.8617,
        longitude: 104.1954,
        borders: JSON.stringify(['AFG', 'BTN', 'MMR', 'IND', 'KAZ', 'PRK', 'KGZ', 'LAO', 'MNG', 'NPL', 'PAK', 'RUS', 'TJK', 'VNM']),
        timezones: JSON.stringify(['Asia/Shanghai']),
      },
    ])
    .returning('*');

  // Geography for France
  const france = countries.find((c: any) => c.code_iso2 === 'FR');
  const allemagne = countries.find((c: any) => c.code_iso2 === 'DE');
  const egypte = countries.find((c: any) => c.code_iso2 === 'EG');
  const grece = countries.find((c: any) => c.code_iso2 === 'GR');

  await knex('country_geography').insert([
    {
      country_id: france.id,
      climate: 'Tempéré océanique à l\'ouest, continental à l\'est, méditerranéen au sud',
      terrain: 'Plaines au nord-ouest, montagnes au sud (Pyrénées) et à l\'est (Alpes, Jura, Vosges)',
      natural_resources: JSON.stringify(['charbon', 'minerai de fer', 'bauxite', 'zinc', 'uranium', 'bois']),
      land_use: JSON.stringify({ arable: '33.5%', forest: '31%', other: '35.5%' }),
      elevation_highest: 'Mont Blanc (4 808 m)',
      elevation_lowest: 'Delta du Rhône (-2 m)',
      coastline_km: 4853,
      description_text: 'La France métropolitaine s\'étend sur 551 695 km². Le pays possède une grande diversité de paysages, des plaines du Bassin parisien aux sommets alpins, en passant par les côtes atlantiques et méditerranéennes.',
    },
    {
      country_id: allemagne.id,
      climate: 'Tempéré continental avec hivers froids et étés chauds',
      terrain: 'Plaines du nord, moyennes montagnes au centre, Alpes au sud',
      natural_resources: JSON.stringify(['charbon', 'lignite', 'gaz naturel', 'sel', 'bois']),
      land_use: JSON.stringify({ arable: '34%', forest: '31.8%', other: '34.2%' }),
      elevation_highest: 'Zugspitze (2 962 m)',
      elevation_lowest: 'Neuendorf-Sachsenbande (-3,5 m)',
      coastline_km: 2389,
      description_text: 'L\'Allemagne est située au cœur de l\'Europe. Son relief varie des plaines du nord aux Alpes bavaroises au sud, traversé par le Rhin et l\'Elbe.',
    },
    {
      country_id: egypte.id,
      climate: 'Désertique aride avec étés très chauds et hivers doux',
      terrain: 'Vaste plateau désertique coupé par la vallée et le delta du Nil',
      natural_resources: JSON.stringify(['pétrole', 'gaz naturel', 'minerai de fer', 'phosphates', 'manganèse']),
      land_use: JSON.stringify({ arable: '3.6%', forest: '0.1%', desert: '96.3%' }),
      elevation_highest: 'Mont Catherine (2 629 m)',
      elevation_lowest: 'Dépression de Qattara (-133 m)',
      coastline_km: 2450,
      description_text: 'L\'Égypte est un pays essentiellement désertique dont la vie se concentre le long du Nil et dans son delta. Le Nil traverse le pays du sud au nord sur plus de 1 500 km.',
    },
    {
      country_id: grece.id,
      climate: 'Méditerranéen avec étés chauds et secs, hivers doux et humides',
      terrain: 'Principalement montagneux avec des plaines côtières, plus de 6 000 îles',
      natural_resources: JSON.stringify(['lignite', 'pétrole', 'minerai de fer', 'bauxite', 'marbre']),
      land_use: JSON.stringify({ arable: '19.7%', forest: '30.5%', other: '49.8%' }),
      elevation_highest: 'Mont Olympe (2 917 m)',
      elevation_lowest: 'Mer Méditerranée (0 m)',
      coastline_km: 13676,
      description_text: 'La Grèce est un pays du sud-est de l\'Europe composé d\'une partie continentale montagneuse et de milliers d\'îles dans les mers Égée et Ionienne.',
    },
  ]);

  // History for France
  await knex('country_history').insert([
    {
      country_id: france.id,
      period: 'Gaule',
      title: 'La Gaule et les Celtes',
      content: 'Avant la conquête romaine, le territoire de la France actuelle est peuplé par les Gaulois, un ensemble de peuples celtes. Ils développent une civilisation riche avec des oppida, pratiquent l\'agriculture et maîtrisent la métallurgie.',
      year_start: -600,
      year_end: -52,
      sort_order: 1,
    },
    {
      country_id: france.id,
      period: 'Gaule romaine',
      title: 'La conquête romaine et la Gaule romaine',
      content: 'Jules César conquiert la Gaule entre 58 et 52 av. J.-C. La bataille d\'Alésia (52 av. J.-C.) marque la défaite de Vercingétorix. La Gaule est romanisée pendant plus de quatre siècles, adoptant la langue latine et le droit romain.',
      year_start: -52,
      year_end: 476,
      sort_order: 2,
    },
    {
      country_id: france.id,
      period: 'Moyen Âge',
      title: 'Le Moyen Âge et les premiers rois',
      content: 'Clovis fonde le royaume des Francs et se convertit au christianisme vers 496. Charlemagne est sacré empereur en 800. Hugues Capet fonde la dynastie capétienne en 987, établissant les bases de la monarchie française.',
      year_start: 476,
      year_end: 1453,
      sort_order: 3,
    },
    {
      country_id: france.id,
      period: 'Renaissance',
      title: 'La Renaissance française',
      content: 'François Ier (1515-1547) importe la Renaissance italienne en France. Construction des châteaux de la Loire, développement des arts et des lettres. L\'édit de Nantes (1598) par Henri IV met fin aux guerres de Religion.',
      year_start: 1453,
      year_end: 1610,
      sort_order: 4,
    },
    {
      country_id: france.id,
      period: 'Monarchie absolue',
      title: 'L\'Ancien Régime et la monarchie absolue',
      content: 'Louis XIV incarne l\'absolutisme royal (1643-1715). Construction du château de Versailles, rayonnement culturel de la France en Europe. Le XVIIIe siècle voit l\'émergence des Lumières avec Voltaire, Rousseau et Montesquieu.',
      year_start: 1610,
      year_end: 1789,
      sort_order: 5,
    },
    {
      country_id: france.id,
      period: 'Révolution',
      title: 'La Révolution française',
      content: 'La prise de la Bastille le 14 juillet 1789 marque le début de la Révolution. Adoption de la Déclaration des droits de l\'homme et du citoyen. La monarchie est abolie en 1792 et la Première République est proclamée.',
      year_start: 1789,
      year_end: 1799,
      sort_order: 6,
    },
    {
      country_id: france.id,
      period: 'Époque contemporaine',
      title: 'La France contemporaine',
      content: 'Napoléon Bonaparte instaure l\'Empire (1804-1815). Après plusieurs régimes, la IIIe République s\'installe durablement (1870). La France traverse les deux guerres mondiales. La Ve République est fondée par de Gaulle en 1958.',
      year_start: 1799,
      year_end: null,
      sort_order: 7,
    },
  ]);

  // History for Egypt
  await knex('country_history').insert([
    {
      country_id: egypte.id,
      period: 'Égypte ancienne',
      title: 'L\'Égypte des pharaons',
      content: 'L\'une des plus anciennes civilisations du monde. Les pharaons règnent pendant plus de 3 000 ans. Construction des pyramides de Gizeh, développement de l\'écriture hiéroglyphique, avancées en médecine et astronomie.',
      year_start: -3100,
      year_end: -30,
      sort_order: 1,
    },
    {
      country_id: egypte.id,
      period: 'Domination étrangère',
      title: 'Conquêtes et dominations étrangères',
      content: 'L\'Égypte est successivement conquise par les Perses, Alexandre le Grand (332 av. J.-C.), les Romains (30 av. J.-C.), puis les Arabes (641). L\'islamisation transforme profondément la culture égyptienne.',
      year_start: -30,
      year_end: 1805,
      sort_order: 2,
    },
    {
      country_id: egypte.id,
      period: 'Époque moderne',
      title: 'L\'Égypte moderne',
      content: 'Méhémet Ali modernise le pays au XIXe siècle. Le canal de Suez est inauguré en 1869. Après le protectorat britannique, l\'Égypte accède à l\'indépendance en 1922. Nasser nationalise le canal de Suez en 1956.',
      year_start: 1805,
      year_end: null,
      sort_order: 3,
    },
  ]);
}
