import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Clear junction tables first (if they exist from migration 010)
  try { await knex('country_quizzes').del(); } catch (_) { /* table may not exist yet */ }
  try { await knex('country_events').del(); } catch (_) { /* table may not exist yet */ }
  await knex('country_history').del();
  await knex('country_geography').del();
  await knex('countries').del();

  const countries = await knex('countries')
    .insert([
      {
        name: 'France',
        official_name: 'République française',
        code_iso2: 'FR',
        code_iso3: 'FRA',
        capital: 'Paris',
        region: 'Europe',
        subregion: 'Europe de l\'Ouest',
        continent: 'Europe',
        population: 67390000,
        area_km2: 551695,
        languages: JSON.stringify({ fr: 'Français' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/fr.png',
        latitude: 46.2276,
        longitude: 2.2137,
        borders: JSON.stringify(['BEL', 'LUX', 'DEU', 'CHE', 'ITA', 'ESP', 'AND', 'MCO']),
        timezones: JSON.stringify(['Europe/Paris']),
        government_type: 'République semi-présidentielle',
        political_summary: 'La France est une république semi-présidentielle fondée par la Constitution de 1958 (Ve République). Le président de la République, élu au suffrage universel pour 5 ans, nomme le Premier ministre. Le Parlement bicaméral comprend l\'Assemblée nationale (577 députés) et le Sénat (348 sénateurs). Membre fondateur de l\'Union européenne, du Conseil de sécurité de l\'ONU (siège permanent) et du G7.',
        gdp_usd: 2780000000000,
        hdi: 0.903,
      },
      {
        name: 'Allemagne',
        official_name: 'République fédérale d\'Allemagne',
        code_iso2: 'DE',
        code_iso3: 'DEU',
        capital: 'Berlin',
        region: 'Europe',
        subregion: 'Europe de l\'Ouest',
        continent: 'Europe',
        population: 83240000,
        area_km2: 357114,
        languages: JSON.stringify({ de: 'Allemand' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/de.png',
        latitude: 51.1657,
        longitude: 10.4515,
        borders: JSON.stringify(['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NLD', 'POL', 'CHE']),
        timezones: JSON.stringify(['Europe/Berlin']),
        government_type: 'République fédérale parlementaire',
        political_summary: 'L\'Allemagne est une république fédérale parlementaire composée de 16 Länder. Le chancelier fédéral, chef du gouvernement, est élu par le Bundestag. Le président fédéral a un rôle essentiellement cérémoniel. Membre fondateur de l\'UE, moteur économique de l\'Europe, membre du G7 et de l\'OTAN.',
        gdp_usd: 4070000000000,
        hdi: 0.942,
      },
      {
        name: 'Italie',
        official_name: 'République italienne',
        code_iso2: 'IT',
        code_iso3: 'ITA',
        capital: 'Rome',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 60360000,
        area_km2: 301340,
        languages: JSON.stringify({ it: 'Italien' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/it.png',
        latitude: 41.8719,
        longitude: 12.5674,
        borders: JSON.stringify(['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT']),
        timezones: JSON.stringify(['Europe/Rome']),
        government_type: 'République parlementaire',
        political_summary: 'L\'Italie est une république parlementaire. Le président de la République est élu par le Parlement pour 7 ans. Le président du Conseil des ministres dirige le gouvernement. Le Parlement bicaméral comprend la Chambre des députés et le Sénat. Membre fondateur de l\'UE, du G7 et de l\'OTAN.',
        gdp_usd: 2010000000000,
        hdi: 0.895,
      },
      {
        name: 'Royaume-Uni',
        official_name: 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord',
        code_iso2: 'GB',
        code_iso3: 'GBR',
        capital: 'Londres',
        region: 'Europe',
        subregion: 'Europe du Nord',
        continent: 'Europe',
        population: 67886000,
        area_km2: 242495,
        languages: JSON.stringify({ en: 'Anglais' }),
        currencies: JSON.stringify({ GBP: { name: 'Livre sterling', symbol: '£' } }),
        flag_url: 'https://flagcdn.com/w320/gb.png',
        latitude: 55.3781,
        longitude: -3.4360,
        borders: JSON.stringify(['IRL']),
        timezones: JSON.stringify(['Europe/London']),
        government_type: 'Monarchie constitutionnelle parlementaire',
        political_summary: 'Le Royaume-Uni est une monarchie constitutionnelle parlementaire. Le monarque est chef de l\'État, le Premier ministre dirige le gouvernement. Le Parlement de Westminster comprend la Chambre des communes (650 députés élus) et la Chambre des Lords. Depuis le Brexit (2020), le pays n\'est plus membre de l\'UE. Membre permanent du Conseil de sécurité de l\'ONU, du G7 et de l\'OTAN.',
        gdp_usd: 3070000000000,
        hdi: 0.929,
      },
      {
        name: 'Espagne',
        official_name: 'Royaume d\'Espagne',
        code_iso2: 'ES',
        code_iso3: 'ESP',
        capital: 'Madrid',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 47350000,
        area_km2: 505992,
        languages: JSON.stringify({ es: 'Espagnol' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/es.png',
        latitude: 40.4637,
        longitude: -3.7492,
        borders: JSON.stringify(['AND', 'FRA', 'GIB', 'PRT', 'MAR']),
        timezones: JSON.stringify(['Europe/Madrid']),
        government_type: 'Monarchie constitutionnelle parlementaire',
        political_summary: 'L\'Espagne est une monarchie constitutionnelle parlementaire depuis la Constitution de 1978. Le roi est chef de l\'État, le président du gouvernement dirige l\'exécutif. Les Cortes Generales comprennent le Congrès des députés et le Sénat. Le pays est organisé en 17 communautés autonomes. Membre de l\'UE et de l\'OTAN.',
        gdp_usd: 1390000000000,
        hdi: 0.905,
      },
      {
        name: 'États-Unis',
        official_name: 'États-Unis d\'Amérique',
        code_iso2: 'US',
        code_iso3: 'USA',
        capital: 'Washington, D.C.',
        region: 'Amérique',
        subregion: 'Amérique du Nord',
        continent: 'Amérique du Nord',
        population: 331900000,
        area_km2: 9833520,
        languages: JSON.stringify({ en: 'Anglais' }),
        currencies: JSON.stringify({ USD: { name: 'Dollar américain', symbol: '$' } }),
        flag_url: 'https://flagcdn.com/w320/us.png',
        latitude: 37.0902,
        longitude: -95.7129,
        borders: JSON.stringify(['CAN', 'MEX']),
        timezones: JSON.stringify(['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles']),
        government_type: 'République fédérale présidentielle',
        political_summary: 'Les États-Unis sont une république fédérale présidentielle composée de 50 États. Le président, élu pour 4 ans, est chef de l\'État et du gouvernement. Le Congrès bicaméral comprend le Sénat (100 sénateurs) et la Chambre des représentants (435 membres). Membre permanent du Conseil de sécurité de l\'ONU, du G7 et de l\'OTAN. Première puissance économique et militaire mondiale.',
        gdp_usd: 25460000000000,
        hdi: 0.921,
      },
      {
        name: 'Japon',
        official_name: 'Japon',
        code_iso2: 'JP',
        code_iso3: 'JPN',
        capital: 'Tokyo',
        region: 'Asie',
        subregion: 'Asie de l\'Est',
        continent: 'Asie',
        population: 125800000,
        area_km2: 377975,
        languages: JSON.stringify({ ja: 'Japonais' }),
        currencies: JSON.stringify({ JPY: { name: 'Yen', symbol: '¥' } }),
        flag_url: 'https://flagcdn.com/w320/jp.png',
        latitude: 36.2048,
        longitude: 138.2529,
        borders: JSON.stringify([]),
        timezones: JSON.stringify(['Asia/Tokyo']),
        government_type: 'Monarchie constitutionnelle parlementaire',
        political_summary: 'Le Japon est une monarchie constitutionnelle parlementaire. L\'empereur est le symbole de l\'État, le Premier ministre dirige le gouvernement. La Diète nationale comprend la Chambre des représentants et la Chambre des conseillers. Troisième puissance économique mondiale, membre du G7. La Constitution de 1947 renonce à la guerre.',
        gdp_usd: 4230000000000,
        hdi: 0.925,
      },
      {
        name: 'Égypte',
        official_name: 'République arabe d\'Égypte',
        code_iso2: 'EG',
        code_iso3: 'EGY',
        capital: 'Le Caire',
        region: 'Afrique',
        subregion: 'Afrique du Nord',
        continent: 'Afrique',
        population: 102300000,
        area_km2: 1002450,
        languages: JSON.stringify({ ar: 'Arabe' }),
        currencies: JSON.stringify({ EGP: { name: 'Livre égyptienne', symbol: '£' } }),
        flag_url: 'https://flagcdn.com/w320/eg.png',
        latitude: 26.8206,
        longitude: 30.8025,
        borders: JSON.stringify(['ISR', 'LBY', 'PSE', 'SDN']),
        timezones: JSON.stringify(['Africa/Cairo']),
        government_type: 'République présidentielle',
        political_summary: 'L\'Égypte est une république présidentielle. Le président est élu au suffrage universel pour un mandat de 6 ans. Le Parlement monocaméral (Chambre des représentants) compte 596 sièges. Pays le plus peuplé du monde arabe, l\'Égypte joue un rôle central dans la géopolitique du Moyen-Orient et de l\'Afrique du Nord.',
        gdp_usd: 476700000000,
        hdi: 0.731,
      },
      {
        name: 'Grèce',
        official_name: 'République hellénique',
        code_iso2: 'GR',
        code_iso3: 'GRC',
        capital: 'Athènes',
        region: 'Europe',
        subregion: 'Europe du Sud',
        continent: 'Europe',
        population: 10720000,
        area_km2: 131957,
        languages: JSON.stringify({ el: 'Grec' }),
        currencies: JSON.stringify({ EUR: { name: 'Euro', symbol: '€' } }),
        flag_url: 'https://flagcdn.com/w320/gr.png',
        latitude: 39.0742,
        longitude: 21.8243,
        borders: JSON.stringify(['ALB', 'BGR', 'TUR', 'MKD']),
        timezones: JSON.stringify(['Europe/Athens']),
        government_type: 'République parlementaire',
        political_summary: 'La Grèce est une république parlementaire. Le président de la République a un rôle essentiellement cérémoniel. Le Premier ministre dirige le gouvernement. Le Parlement monocaméral (Vouli) compte 300 députés. Berceau de la démocratie, la Grèce est membre de l\'UE depuis 1981 et de l\'OTAN.',
        gdp_usd: 219100000000,
        hdi: 0.887,
      },
      {
        name: 'Chine',
        official_name: 'République populaire de Chine',
        code_iso2: 'CN',
        code_iso3: 'CHN',
        capital: 'Pékin',
        region: 'Asie',
        subregion: 'Asie de l\'Est',
        continent: 'Asie',
        population: 1412000000,
        area_km2: 9596961,
        languages: JSON.stringify({ zh: 'Chinois mandarin' }),
        currencies: JSON.stringify({ CNY: { name: 'Yuan', symbol: '¥' } }),
        flag_url: 'https://flagcdn.com/w320/cn.png',
        latitude: 35.8617,
        longitude: 104.1954,
        borders: JSON.stringify(['AFG', 'BTN', 'MMR', 'IND', 'KAZ', 'PRK', 'KGZ', 'LAO', 'MNG', 'NPL', 'PAK', 'RUS', 'TJK', 'VNM']),
        timezones: JSON.stringify(['Asia/Shanghai']),
        government_type: 'République socialiste à parti unique',
        political_summary: 'La Chine est une république socialiste dirigée par le Parti communiste chinois (PCC). Le président de la République est aussi secrétaire général du PCC. L\'Assemblée nationale populaire est l\'organe législatif suprême. Deuxième puissance économique mondiale, membre permanent du Conseil de sécurité de l\'ONU. Le système politique repose sur la centralisation du pouvoir par le PCC.',
        gdp_usd: 17960000000000,
        hdi: 0.768,
      },
    ])
    .returning('*');

  // Geography for France
  const france = countries.find((c: any) => c.code_iso2 === 'FR');
  const allemagne = countries.find((c: any) => c.code_iso2 === 'DE');
  const egypte = countries.find((c: any) => c.code_iso2 === 'EG');
  const grece = countries.find((c: any) => c.code_iso2 === 'GR');

  await knex('country_geography').insert([
    {
      country_id: france.id,
      climate: 'Tempéré océanique à l\'ouest, continental à l\'est, méditerranéen au sud',
      terrain: 'Plaines au nord-ouest, montagnes au sud (Pyrénées) et à l\'est (Alpes, Jura, Vosges)',
      natural_resources: JSON.stringify(['charbon', 'minerai de fer', 'bauxite', 'zinc', 'uranium', 'bois']),
      land_use: JSON.stringify({ arable: '33.5%', forest: '31%', other: '35.5%' }),
      elevation_highest: 'Mont Blanc (4 808 m)',
      elevation_lowest: 'Delta du Rhône (-2 m)',
      coastline_km: 4853,
      description_text: 'La France métropolitaine s\'étend sur 551 695 km². Le pays possède une grande diversité de paysages, des plaines du Bassin parisien aux sommets alpins, en passant par les côtes atlantiques et méditerranéennes.',
    },
    {
      country_id: allemagne.id,
      climate: 'Tempéré continental avec hivers froids et étés chauds',
      terrain: 'Plaines du nord, moyennes montagnes au centre, Alpes au sud',
      natural_resources: JSON.stringify(['charbon', 'lignite', 'gaz naturel', 'sel', 'bois']),
      land_use: JSON.stringify({ arable: '34%', forest: '31.8%', other: '34.2%' }),
      elevation_highest: 'Zugspitze (2 962 m)',
      elevation_lowest: 'Neuendorf-Sachsenbande (-3,5 m)',
      coastline_km: 2389,
      description_text: 'L\'Allemagne est située au cœur de l\'Europe. Son relief varie des plaines du nord aux Alpes bavaroises au sud, traversé par le Rhin et l\'Elbe.',
    },
    {
      country_id: egypte.id,
      climate: 'Désertique aride avec étés très chauds et hivers doux',
      terrain: 'Vaste plateau désertique coupé par la vallée et le delta du Nil',
      natural_resources: JSON.stringify(['pétrole', 'gaz naturel', 'minerai de fer', 'phosphates', 'manganèse']),
      land_use: JSON.stringify({ arable: '3.6%', forest: '0.1%', desert: '96.3%' }),
      elevation_highest: 'Mont Catherine (2 629 m)',
      elevation_lowest: 'Dépression de Qattara (-133 m)',
      coastline_km: 2450,
      description_text: 'L\'Égypte est un pays essentiellement désertique dont la vie se concentre le long du Nil et dans son delta. Le Nil traverse le pays du sud au nord sur plus de 1 500 km.',
    },
    {
      country_id: grece.id,
      climate: 'Méditerranéen avec étés chauds et secs, hivers doux et humides',
      terrain: 'Principalement montagneux avec des plaines côtières, plus de 6 000 îles',
      natural_resources: JSON.stringify(['lignite', 'pétrole', 'minerai de fer', 'bauxite', 'marbre']),
      land_use: JSON.stringify({ arable: '19.7%', forest: '30.5%', other: '49.8%' }),
      elevation_highest: 'Mont Olympe (2 917 m)',
      elevation_lowest: 'Mer Méditerranée (0 m)',
      coastline_km: 13676,
      description_text: 'La Grèce est un pays du sud-est de l\'Europe composé d\'une partie continentale montagneuse et de milliers d\'îles dans les mers Égée et Ionienne.',
    },
  ]);

  // History for France
  await knex('country_history').insert([
    {
      country_id: france.id,
      period: 'Gaule',
      title: 'La Gaule et les Celtes',
      content: 'Avant la conquête romaine, le territoire de la France actuelle est peuplé par les Gaulois, un ensemble de peuples celtes. Ils développent une civilisation riche avec des oppida, pratiquent l\'agriculture et maîtrisent la métallurgie.',
      year_start: -600,
      year_end: -52,
      sort_order: 1,
    },
    {
      country_id: france.id,
      period: 'Gaule romaine',
      title: 'La conquête romaine et la Gaule romaine',
      content: 'Jules César conquiert la Gaule entre 58 et 52 av. J.-C. La bataille d\'Alésia (52 av. J.-C.) marque la défaite de Vercingétorix. La Gaule est romanisée pendant plus de quatre siècles, adoptant la langue latine et le droit romain.',
      year_start: -52,
      year_end: 476,
      sort_order: 2,
    },
    {
      country_id: france.id,
      period: 'Moyen Âge',
      title: 'Le Moyen Âge et les premiers rois',
      content: 'Clovis fonde le royaume des Francs et se convertit au christianisme vers 496. Charlemagne est sacré empereur en 800. Hugues Capet fonde la dynastie capétienne en 987, établissant les bases de la monarchie française.',
      year_start: 476,
      year_end: 1453,
      sort_order: 3,
    },
    {
      country_id: france.id,
      period: 'Renaissance',
      title: 'La Renaissance française',
      content: 'François Ier (1515-1547) importe la Renaissance italienne en France. Construction des châteaux de la Loire, développement des arts et des lettres. L\'édit de Nantes (1598) par Henri IV met fin aux guerres de Religion.',
      year_start: 1453,
      year_end: 1610,
      sort_order: 4,
    },
    {
      country_id: france.id,
      period: 'Monarchie absolue',
      title: 'L\'Ancien Régime et la monarchie absolue',
      content: 'Louis XIV incarne l\'absolutisme royal (1643-1715). Construction du château de Versailles, rayonnement culturel de la France en Europe. Le XVIIIe siècle voit l\'émergence des Lumières avec Voltaire, Rousseau et Montesquieu.',
      year_start: 1610,
      year_end: 1789,
      sort_order: 5,
    },
    {
      country_id: france.id,
      period: 'Révolution',
      title: 'La Révolution française',
      content: 'La prise de la Bastille le 14 juillet 1789 marque le début de la Révolution. Adoption de la Déclaration des droits de l\'homme et du citoyen. La monarchie est abolie en 1792 et la Première République est proclamée.',
      year_start: 1789,
      year_end: 1799,
      sort_order: 6,
    },
    {
      country_id: france.id,
      period: 'Époque contemporaine',
      title: 'La France contemporaine',
      content: 'Napoléon Bonaparte instaure l\'Empire (1804-1815). Après plusieurs régimes, la IIIe République s\'installe durablement (1870). La France traverse les deux guerres mondiales. La Ve République est fondée par de Gaulle en 1958.',
      year_start: 1799,
      year_end: null,
      sort_order: 7,
    },
  ]);

  const italie = countries.find((c: any) => c.code_iso2 === 'IT');
  const royaumeUni = countries.find((c: any) => c.code_iso2 === 'GB');
  const espagne = countries.find((c: any) => c.code_iso2 === 'ES');
  const usa = countries.find((c: any) => c.code_iso2 === 'US');
  const japon = countries.find((c: any) => c.code_iso2 === 'JP');
  const chine = countries.find((c: any) => c.code_iso2 === 'CN');

  // History for Germany
  await knex('country_history').insert([
    {
      country_id: allemagne.id,
      period: 'Germanie antique',
      title: 'Les peuples germaniques',
      content: 'Les tribus germaniques occupent l\'Europe centrale. La victoire d\'Arminius sur les Romains à la bataille de Teutobourg (9 ap. J.-C.) stoppe l\'expansion romaine au-delà du Rhin.',
      year_start: -500,
      year_end: 843,
      sort_order: 1,
    },
    {
      country_id: allemagne.id,
      period: 'Saint-Empire',
      title: 'Le Saint-Empire romain germanique',
      content: 'Otton Ier est couronné empereur en 962. Le Saint-Empire domine l\'Europe centrale pendant des siècles. La Réforme de Luther (1517) divise l\'Allemagne entre catholiques et protestants. La guerre de Trente Ans (1618-1648) dévaste le pays.',
      year_start: 843,
      year_end: 1806,
      sort_order: 2,
    },
    {
      country_id: allemagne.id,
      period: 'Unification',
      title: 'L\'unification allemande',
      content: 'Bismarck unifie l\'Allemagne sous la Prusse. L\'Empire allemand est proclamé à Versailles en 1871. L\'Allemagne devient une puissance industrielle majeure.',
      year_start: 1806,
      year_end: 1918,
      sort_order: 3,
    },
    {
      country_id: allemagne.id,
      period: 'Époque contemporaine',
      title: 'L\'Allemagne contemporaine',
      content: 'La République de Weimar (1918-1933) cède au nazisme. Après la Seconde Guerre mondiale, l\'Allemagne est divisée en RFA et RDA. La chute du mur de Berlin (1989) mène à la réunification (1990). L\'Allemagne réunifiée est aujourd\'hui le moteur économique de l\'Europe.',
      year_start: 1918,
      year_end: null,
      sort_order: 4,
    },
  ]);

  // History for Italy
  await knex('country_history').insert([
    {
      country_id: italie.id,
      period: 'Antiquité',
      title: 'Rome antique',
      content: 'Rome est fondée en 753 av. J.-C. selon la tradition. La République romaine puis l\'Empire romain dominent la Méditerranée pendant des siècles. L\'Empire romain d\'Occident chute en 476.',
      year_start: -753,
      year_end: 476,
      sort_order: 1,
    },
    {
      country_id: italie.id,
      period: 'Moyen Âge et Renaissance',
      title: 'Les cités-États et la Renaissance',
      content: 'L\'Italie médiévale est morcelée en cités-États (Florence, Venise, Gênes, Milan). La Renaissance (XIVe-XVIe siècle) fait de l\'Italie le centre culturel et artistique de l\'Europe avec Léonard de Vinci, Michel-Ange et Raphaël.',
      year_start: 476,
      year_end: 1796,
      sort_order: 2,
    },
    {
      country_id: italie.id,
      period: 'Unification et époque contemporaine',
      title: 'Le Risorgimento et l\'Italie moderne',
      content: 'Le mouvement du Risorgimento mène à l\'unification italienne (1861) sous la maison de Savoie. Garibaldi et Cavour en sont les figures clés. Après le fascisme de Mussolini et la Seconde Guerre mondiale, l\'Italie devient une république en 1946.',
      year_start: 1796,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for United Kingdom
  await knex('country_history').insert([
    {
      country_id: royaumeUni.id,
      period: 'Antiquité et Moyen Âge',
      title: 'De la Bretagne romaine aux royaumes médiévaux',
      content: 'La Bretagne est conquise par les Romains en 43 ap. J.-C. Après leur départ, les Anglo-Saxons s\'installent. Guillaume le Conquérant envahit l\'Angleterre en 1066. La Magna Carta (1215) pose les bases du parlementarisme.',
      year_start: 43,
      year_end: 1485,
      sort_order: 1,
    },
    {
      country_id: royaumeUni.id,
      period: 'Époque moderne',
      title: 'L\'ère Tudor et l\'Empire britannique',
      content: 'Henri VIII rompt avec Rome (1534). L\'ère élisabéthaine voit le début de l\'expansion coloniale. La Révolution anglaise (1642-1651) et la Glorieuse Révolution (1688) établissent la monarchie parlementaire. L\'Empire britannique devient le plus vaste de l\'histoire.',
      year_start: 1485,
      year_end: 1901,
      sort_order: 2,
    },
    {
      country_id: royaumeUni.id,
      period: 'Époque contemporaine',
      title: 'Le Royaume-Uni contemporain',
      content: 'Le Royaume-Uni joue un rôle central dans les deux guerres mondiales. La décolonisation après 1945 met fin à l\'Empire. Le pays rejoint la CEE en 1973 puis quitte l\'UE en 2020 (Brexit). Il reste une puissance diplomatique et financière mondiale.',
      year_start: 1901,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for Spain
  await knex('country_history').insert([
    {
      country_id: espagne.id,
      period: 'Antiquité et Moyen Âge',
      title: 'De l\'Hispanie romaine à la Reconquista',
      content: 'L\'Hispanie est une province romaine majeure. Les Wisigoths puis les Maures (711) dominent la péninsule. La Reconquista chrétienne s\'achève avec la prise de Grenade en 1492, année de la découverte de l\'Amérique par Christophe Colomb.',
      year_start: -218,
      year_end: 1492,
      sort_order: 1,
    },
    {
      country_id: espagne.id,
      period: 'Siècle d\'Or',
      title: 'L\'Empire espagnol et le Siècle d\'Or',
      content: 'L\'Espagne bâtit un immense empire colonial en Amérique. Le Siècle d\'Or (XVIe-XVIIe siècle) est une période de rayonnement culturel avec Cervantes, Velázquez et El Greco. Le déclin s\'amorce après la défaite de l\'Invincible Armada (1588).',
      year_start: 1492,
      year_end: 1808,
      sort_order: 2,
    },
    {
      country_id: espagne.id,
      period: 'Époque contemporaine',
      title: 'L\'Espagne contemporaine',
      content: 'Guerre d\'indépendance contre Napoléon, perte des colonies au XIXe siècle. La guerre civile (1936-1939) mène à la dictature de Franco. Après sa mort (1975), la transition démocratique s\'opère. L\'Espagne rejoint l\'UE en 1986.',
      year_start: 1808,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for United States
  await knex('country_history').insert([
    {
      country_id: usa.id,
      period: 'Colonisation',
      title: 'L\'Amérique coloniale',
      content: 'Les premiers colons européens s\'installent à Jamestown (1607) et Plymouth (1620). Treize colonies britanniques se développent le long de la côte atlantique. Les tensions fiscales avec la Grande-Bretagne mènent à la révolte.',
      year_start: 1607,
      year_end: 1776,
      sort_order: 1,
    },
    {
      country_id: usa.id,
      period: 'Indépendance et expansion',
      title: 'La naissance des États-Unis',
      content: 'La Déclaration d\'indépendance est signée le 4 juillet 1776. La Constitution (1787) établit une république fédérale. Le pays s\'étend vers l\'ouest (Manifest Destiny). La guerre de Sécession (1861-1865) aboutit à l\'abolition de l\'esclavage.',
      year_start: 1776,
      year_end: 1898,
      sort_order: 2,
    },
    {
      country_id: usa.id,
      period: 'Puissance mondiale',
      title: 'Les États-Unis, superpuissance',
      content: 'Les États-Unis émergent comme puissance mondiale après 1918. Après la Seconde Guerre mondiale, ils deviennent une superpuissance face à l\'URSS (Guerre froide). Depuis 1991, ils restent la première puissance économique et militaire mondiale.',
      year_start: 1898,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for Japan
  await knex('country_history').insert([
    {
      country_id: japon.id,
      period: 'Japon ancien',
      title: 'Le Japon ancien et féodal',
      content: 'La civilisation japonaise se développe dès la période Jōmon. Le premier État japonais se forme au IVe siècle. L\'ère des samouraïs et des shoguns domine du XIIe au XIXe siècle. Le Japon reste largement isolé du monde extérieur pendant la période Edo (1603-1868).',
      year_start: -300,
      year_end: 1868,
      sort_order: 1,
    },
    {
      country_id: japon.id,
      period: 'Ère Meiji et expansion',
      title: 'La modernisation et l\'expansion',
      content: 'La restauration Meiji (1868) transforme le Japon en puissance industrielle moderne. Victoires militaires contre la Chine (1895) et la Russie (1905). L\'expansion impérialiste en Asie mène à la Seconde Guerre mondiale et à la défaite de 1945.',
      year_start: 1868,
      year_end: 1945,
      sort_order: 2,
    },
    {
      country_id: japon.id,
      period: 'Japon contemporain',
      title: 'Le miracle économique japonais',
      content: 'Après la défaite de 1945, le Japon se reconstruit sous l\'occupation américaine. Le « miracle économique » en fait la deuxième puissance mondiale dans les années 1980. Malgré des décennies de stagnation, le Japon reste une puissance technologique et culturelle majeure.',
      year_start: 1945,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for Greece
  await knex('country_history').insert([
    {
      country_id: grece.id,
      period: 'Grèce antique',
      title: 'Le berceau de la civilisation occidentale',
      content: 'La Grèce antique invente la démocratie, la philosophie et le théâtre. Les cités-États (Athènes, Sparte) s\'affrontent et résistent aux Perses (Marathon, Thermopyles, Salamine). Alexandre le Grand conquiert un immense empire jusqu\'en Inde.',
      year_start: -800,
      year_end: -146,
      sort_order: 1,
    },
    {
      country_id: grece.id,
      period: 'Domination étrangère',
      title: 'De Rome à l\'Empire ottoman',
      content: 'La Grèce est conquise par Rome (146 av. J.-C.), puis fait partie de l\'Empire byzantin. Constantinople tombe en 1453 et la Grèce passe sous domination ottomane pendant près de quatre siècles.',
      year_start: -146,
      year_end: 1821,
      sort_order: 2,
    },
    {
      country_id: grece.id,
      period: 'Grèce moderne',
      title: 'L\'indépendance et la Grèce moderne',
      content: 'La guerre d\'indépendance (1821-1829) libère la Grèce de l\'Empire ottoman. Le pays s\'agrandit au XIXe et XXe siècles. Après la dictature des colonels (1967-1974), la Grèce rejoint la CEE en 1981 et adopte l\'euro en 2001.',
      year_start: 1821,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for China
  await knex('country_history').insert([
    {
      country_id: chine.id,
      period: 'Chine impériale',
      title: 'Les dynasties chinoises',
      content: 'La Chine est l\'une des plus anciennes civilisations continues. Les dynasties Shang, Zhou, Qin (Grande Muraille), Han (Route de la soie), Tang et Song développent des inventions majeures : papier, imprimerie, boussole, poudre à canon.',
      year_start: -1600,
      year_end: 1644,
      sort_order: 1,
    },
    {
      country_id: chine.id,
      period: 'Déclin et révolutions',
      title: 'La fin de l\'Empire et les révolutions',
      content: 'La dynastie Qing (1644-1912) voit le déclin face aux puissances occidentales (guerres de l\'opium). La république est proclamée en 1912 par Sun Yat-sen. La guerre civile oppose nationalistes et communistes. Mao Zedong proclame la République populaire en 1949.',
      year_start: 1644,
      year_end: 1949,
      sort_order: 2,
    },
    {
      country_id: chine.id,
      period: 'Chine contemporaine',
      title: 'La Chine contemporaine',
      content: 'Sous Mao, la Chine connaît le Grand Bond en avant et la Révolution culturelle. Deng Xiaoping lance les réformes économiques en 1978. La Chine devient la deuxième puissance économique mondiale et un acteur géopolitique incontournable.',
      year_start: 1949,
      year_end: null,
      sort_order: 3,
    },
  ]);

  // History for Egypt
  await knex('country_history').insert([
    {
      country_id: egypte.id,
      period: 'Égypte ancienne',
      title: 'L\'Égypte des pharaons',
      content: 'L\'une des plus anciennes civilisations du monde. Les pharaons règnent pendant plus de 3 000 ans. Construction des pyramides de Gizeh, développement de l\'écriture hiéroglyphique, avancées en médecine et astronomie.',
      year_start: -3100,
      year_end: -30,
      sort_order: 1,
    },
    {
      country_id: egypte.id,
      period: 'Domination étrangère',
      title: 'Conquêtes et dominations étrangères',
      content: 'L\'Égypte est successivement conquise par les Perses, Alexandre le Grand (332 av. J.-C.), les Romains (30 av. J.-C.), puis les Arabes (641). L\'islamisation transforme profondément la culture égyptienne.',
      year_start: -30,
      year_end: 1805,
      sort_order: 2,
    },
    {
      country_id: egypte.id,
      period: 'Époque moderne',
      title: 'L\'Égypte moderne',
      content: 'Méhémet Ali modernise le pays au XIXe siècle. Le canal de Suez est inauguré en 1869. Après le protectorat britannique, l\'Égypte accède à l\'indépendance en 1922. Nasser nationalise le canal de Suez en 1956.',
      year_start: 1805,
      year_end: null,
      sort_order: 3,
    },
  ]);
}
