import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('person_contributions').del();
  await knex('persons').del();

  const persons = await knex('persons')
    .insert([
      // ═══════════════════════════════════════════════════════════════
      // PHILOSOPHES
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'socrate',
        first_name: 'Socrate',
        last_name: '',
        full_name: 'Socrate',
        birth_date: '470 av. J.-C.',
        death_date: '399 av. J.-C.',
        birth_place: 'Athènes, Grèce',
        death_place: 'Athènes, Grèce',
        nationality: 'Grecque',
        category: 'philosopher',
        subcategory: 'Philosophie antique',
        summary: 'Philosophe grec fondateur de la philosophie occidentale, connu pour sa méthode de questionnement (maïeutique).',
        biography_text: 'Socrate est considéré comme le père de la philosophie occidentale. Il n\'a laissé aucun écrit, et sa pensée nous est parvenue à travers les dialogues de son élève Platon. Sa méthode, la maïeutique, consiste à faire « accoucher » les esprits de leurs connaissances par le questionnement. Accusé de corrompre la jeunesse et de ne pas reconnaître les dieux de la cité, il est condamné à mort et boit la ciguë en 399 av. J.-C.',
        notable_works: JSON.stringify(['Méthode maïeutique', 'Dialogues socratiques (via Platon)']),
        quotes: JSON.stringify(['Je sais que je ne sais rien', 'Connais-toi toi-même', 'Une vie sans examen ne vaut pas la peine d\'être vécue']),
        era: 'antiquite',
        historical_importance: 'Socrate a fondé la tradition philosophique occidentale. Sa méthode de questionnement critique a influencé toute la pensée européenne, de Platon et Aristote jusqu\'aux philosophes modernes. Il est le premier à placer l\'éthique et la recherche de la vérité au centre de la philosophie.',
        anecdote: 'L\'oracle de Delphes avait déclaré Socrate « le plus sage des hommes ». Socrate, surpris, entreprit d\'interroger ceux qui se croyaient sages pour comprendre cette affirmation. Il conclut que sa sagesse résidait dans le fait qu\'il savait qu\'il ne savait rien, contrairement aux autres.',
      },
      {
        slug: 'platon',
        first_name: 'Platon',
        last_name: '',
        full_name: 'Platon',
        birth_date: '428 av. J.-C.',
        death_date: '348 av. J.-C.',
        birth_place: 'Athènes, Grèce',
        death_place: 'Athènes, Grèce',
        nationality: 'Grecque',
        category: 'philosopher',
        subcategory: 'Philosophie antique',
        summary: 'Élève de Socrate, fondateur de l\'Académie d\'Athènes, auteur de la théorie des Idées.',
        biography_text: 'Platon est l\'un des penseurs les plus influents de l\'histoire. Élève de Socrate, il fonde l\'Académie d\'Athènes vers 387 av. J.-C., considérée comme la première université du monde occidental. Sa philosophie repose sur la théorie des Idées : le monde sensible n\'est qu\'une copie imparfaite d\'un monde intelligible parfait. Ses dialogues (La République, Le Banquet, Phèdre) explorent la justice, l\'amour, la connaissance et la politique.',
        notable_works: JSON.stringify(['La République', 'Le Banquet', 'Phèdre', 'Phédon', 'Timée']),
        quotes: JSON.stringify(['La nécessité est mère de l\'invention', 'L\'ignorance est la racine de tout mal', 'On peut en savoir plus sur quelqu\'un en une heure de jeu qu\'en un an de conversation']),
        era: 'antiquite',
        historical_importance: 'Platon a posé les fondations de la métaphysique, de l\'épistémologie et de la philosophie politique occidentales. L\'Académie qu\'il a fondée a fonctionné pendant près de 900 ans. Le philosophe Alfred North Whitehead a dit que toute la philosophie occidentale n\'était qu\'une « série de notes en bas de page de Platon ».',
        anecdote: 'Le vrai nom de Platon était Aristoclès. « Platon » était un surnom signifiant « large » (platus en grec), donné par son professeur de gymnastique en raison de sa carrure imposante. Ce surnom est devenu si célèbre que son vrai nom est tombé dans l\'oubli.',
      },
      {
        slug: 'rene-descartes',
        first_name: 'René',
        last_name: 'Descartes',
        full_name: 'René Descartes',
        birth_date: '31 mars 1596',
        death_date: '11 février 1650',
        birth_place: 'La Haye-en-Touraine, France',
        death_place: 'Stockholm, Suède',
        nationality: 'Française',
        category: 'philosopher',
        subcategory: 'Rationalisme',
        summary: 'Père de la philosophie moderne et du rationalisme, mathématicien et scientifique.',
        biography_text: 'René Descartes est considéré comme le fondateur de la philosophie moderne. Son « Discours de la méthode » (1637) établit les bases du rationalisme : douter de tout pour ne garder que les certitudes. Son célèbre « Je pense, donc je suis » (Cogito ergo sum) est le point de départ de toute sa philosophie. Mathématicien brillant, il invente le système de coordonnées cartésiennes qui unit algèbre et géométrie.',
        notable_works: JSON.stringify(['Discours de la méthode', 'Méditations métaphysiques', 'Les Principes de la philosophie', 'Géométrie']),
        quotes: JSON.stringify(['Je pense, donc je suis', 'Le bon sens est la chose du monde la mieux partagée', 'Pour atteindre la vérité, il faut une fois dans sa vie se défaire de toutes les opinions que l\'on a reçues']),
        era: 'temps_modernes',
        historical_importance: 'Descartes a révolutionné la philosophie en plaçant la raison et le doute méthodique au centre de la recherche de la vérité. Il est aussi le père de la géométrie analytique (coordonnées cartésiennes), pont entre algèbre et géométrie qui a rendu possible le calcul infinitésimal de Newton et Leibniz.',
        anecdote: 'Descartes avait l\'habitude de rester au lit jusqu\'à midi pour méditer. Quand la reine Christine de Suède l\'invita à Stockholm et exigea des cours de philosophie à 5 heures du matin, le changement de rythme dans le froid suédois lui fut fatal : il mourut d\'une pneumonie quelques mois plus tard.',
      },

      // ═══════════════════════════════════════════════════════════════
      // PHYSICIENS
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'albert-einstein',
        first_name: 'Albert',
        last_name: 'Einstein',
        full_name: 'Albert Einstein',
        birth_date: '14 mars 1879',
        death_date: '18 avril 1955',
        birth_place: 'Ulm, Allemagne',
        death_place: 'Princeton, États-Unis',
        nationality: 'Allemande / Suisse / Américaine',
        category: 'scientist',
        subcategory: 'Physicien',
        summary: 'Physicien théoricien, auteur de la théorie de la relativité et prix Nobel de physique 1921.',
        biography_text: 'Albert Einstein révolutionne la physique au début du XXe siècle. En 1905, son « annus mirabilis », il publie quatre articles fondamentaux, dont la relativité restreinte et l\'explication de l\'effet photoélectrique (qui lui vaut le Nobel en 1921). En 1915, il formule la relativité générale, qui redéfinit notre compréhension de la gravité, de l\'espace et du temps. Fuyant le nazisme, il s\'installe aux États-Unis en 1933.',
        notable_works: JSON.stringify(['Relativité restreinte (E=mc²)', 'Relativité générale', 'Effet photoélectrique', 'Mouvement brownien']),
        quotes: JSON.stringify(['L\'imagination est plus importante que le savoir', 'La folie, c\'est de faire toujours la même chose et de s\'attendre à un résultat différent', 'Dieu ne joue pas aux dés']),
        era: 'epoque_contemporaine',
        historical_importance: 'Einstein a complètement transformé notre compréhension de l\'univers. La relativité générale explique la gravité comme une courbure de l\'espace-temps. E=mc² a ouvert la voie à l\'énergie nucléaire. Ses travaux sur l\'effet photoélectrique ont posé les bases de la mécanique quantique.',
        anecdote: 'Einstein avait échoué à l\'examen d\'entrée de l\'École polytechnique de Zurich à sa première tentative. Il a aussi travaillé comme employé de bureau des brevets à Berne, période pendant laquelle il a publié ses articles les plus révolutionnaires de 1905.',
      },
      {
        slug: 'isaac-newton',
        first_name: 'Isaac',
        last_name: 'Newton',
        full_name: 'Isaac Newton',
        birth_date: '4 janvier 1643',
        death_date: '31 mars 1727',
        birth_place: 'Woolsthorpe, Angleterre',
        death_place: 'Londres, Angleterre',
        nationality: 'Anglaise',
        category: 'scientist',
        subcategory: 'Physicien',
        summary: 'Physicien et mathématicien, auteur des lois de la gravitation universelle et du mouvement.',
        biography_text: 'Isaac Newton est l\'un des scientifiques les plus influents de tous les temps. Ses Principia Mathematica (1687) posent les lois du mouvement et de la gravitation universelle, unifiant la mécanique céleste et terrestre. Il co-invente le calcul infinitésimal (indépendamment de Leibniz), découvre la décomposition de la lumière blanche par un prisme, et invente le télescope à réflexion. Il est anobli et préside la Royal Society.',
        notable_works: JSON.stringify(['Principia Mathematica', 'Opticks', 'Calcul infinitésimal', 'Lois du mouvement', 'Loi de la gravitation universelle']),
        quotes: JSON.stringify(['Si j\'ai vu plus loin, c\'est en montant sur les épaules de géants', 'Ce que nous savons est une goutte d\'eau ; ce que nous ignorons est l\'océan']),
        era: 'temps_modernes',
        historical_importance: 'Newton a unifié la physique terrestre et céleste en une seule théorie. Ses trois lois du mouvement et la loi de la gravitation universelle ont dominé la physique pendant plus de 200 ans, jusqu\'à Einstein. Le calcul infinitésimal qu\'il a développé est devenu l\'outil mathématique fondamental de toutes les sciences.',
        anecdote: 'La légende de la pomme tombant sur la tête de Newton est probablement exagérée, mais Newton lui-même a raconté qu\'observer une pomme tomber d\'un arbre dans le verger familial l\'avait amené à réfléchir à la gravité. Pendant l\'épidémie de peste de 1665-1666, confiné chez lui, il fit ses découvertes les plus importantes.',
      },
      {
        slug: 'marie-curie',
        first_name: 'Marie',
        last_name: 'Curie',
        full_name: 'Marie Curie',
        birth_date: '7 novembre 1867',
        death_date: '4 juillet 1934',
        birth_place: 'Varsovie, Pologne',
        death_place: 'Passy, France',
        nationality: 'Polonaise / Française',
        category: 'scientist',
        subcategory: 'Physicienne',
        summary: 'Première femme à recevoir un prix Nobel, pionnière de la recherche sur la radioactivité.',
        biography_text: 'Maria Sklodowska, devenue Marie Curie, quitte la Pologne pour étudier à Paris. Avec son mari Pierre Curie, elle découvre le polonium et le radium. Elle est la première femme professeure à la Sorbonne et la seule personne à avoir reçu des prix Nobel dans deux disciplines scientifiques différentes (physique en 1903, chimie en 1911). Ses travaux sur la radioactivité ont révolutionné la physique et la médecine.',
        notable_works: JSON.stringify(['Découverte du polonium', 'Découverte du radium', 'Recherches sur la radioactivité', 'Petites Curies (radiologie mobile)']),
        quotes: JSON.stringify(['Dans la vie, rien n\'est à craindre, tout est à comprendre', 'On ne fait jamais attention à ce qui a été fait ; on ne voit que ce qui reste à faire', 'Soyez moins curieux des personnes que de leurs idées']),
        era: 'epoque_contemporaine',
        historical_importance: 'Marie Curie a ouvert le champ de la physique nucléaire. Ses découvertes ont conduit à la radiothérapie contre le cancer. Première femme lauréate du Nobel, elle a brisé les barrières de genre dans les sciences. Pendant la Première Guerre mondiale, elle a créé des unités mobiles de radiographie (les « Petites Curies ») qui ont sauvé des milliers de vies.',
        anecdote: 'Les cahiers de laboratoire de Marie Curie sont encore radioactifs plus d\'un siècle après, et doivent être conservés dans des boîtes doublées de plomb. Pour les consulter, il faut porter des vêtements de protection et signer une décharge.',
      },
      {
        slug: 'galilee',
        first_name: 'Galileo',
        last_name: 'Galilei',
        full_name: 'Galilée',
        birth_date: '15 février 1564',
        death_date: '8 janvier 1642',
        birth_place: 'Pise, Italie',
        death_place: 'Arcetri, Italie',
        nationality: 'Italienne',
        category: 'scientist',
        subcategory: 'Physicien',
        summary: 'Père de la physique moderne et de l\'astronomie d\'observation, défenseur de l\'héliocentrisme.',
        biography_text: 'Galilée est le père de la science moderne. Avec sa lunette astronomique, il découvre les montagnes de la Lune, les satellites de Jupiter, les phases de Vénus et les taches solaires. Ces observations confirment le système héliocentrique de Copernic. Ses travaux sur la chute des corps et le mouvement fondent la physique moderne. Condamné par l\'Inquisition en 1633, il est assigné à résidence jusqu\'à sa mort.',
        notable_works: JSON.stringify(['Dialogue sur les deux grands systèmes du monde', 'Discours sur deux sciences nouvelles', 'Le Messager céleste', 'Lunette astronomique perfectionnée']),
        quotes: JSON.stringify(['Et pourtant elle tourne', 'Mesurez ce qui est mesurable et rendez mesurable ce qui ne l\'est pas', 'Le livre de la nature est écrit en langage mathématique']),
        era: 'temps_modernes',
        historical_importance: 'Galilée a fondé la méthode scientifique moderne basée sur l\'observation et l\'expérimentation. Son conflit avec l\'Église catholique symbolise la tension entre science et dogme religieux. Ses lois sur la chute des corps ont directement inspiré Newton.',
        anecdote: 'La phrase « Et pourtant elle tourne » (Eppur si muove), que Galilée aurait murmurée après avoir été forcé d\'abjurer l\'héliocentrisme devant l\'Inquisition, est probablement légendaire. En réalité, Galilée a prudemment accepté sa condamnation pour éviter le sort de Giordano Bruno, brûlé vif 33 ans plus tôt.',
      },

      // ═══════════════════════════════════════════════════════════════
      // MATHÉMATICIENS
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'pythagore',
        first_name: 'Pythagore',
        last_name: 'de Samos',
        full_name: 'Pythagore',
        birth_date: '570 av. J.-C.',
        death_date: '495 av. J.-C.',
        birth_place: 'Samos, Grèce',
        death_place: 'Métaponte, Italie',
        nationality: 'Grecque',
        category: 'scientist',
        subcategory: 'Mathématicien',
        summary: 'Mathématicien et philosophe grec, auteur du célèbre théorème qui porte son nom.',
        biography_text: 'Pythagore fonde une école philosophique et mathématique à Crotone (sud de l\'Italie). Il considère que « tout est nombre » et que les mathématiques sont la clé pour comprendre l\'univers. Son théorème sur les triangles rectangles (a² + b² = c²) est l\'un des résultats les plus fondamentaux de la géométrie. Il découvre aussi les rapports musicaux harmoniques et établit des liens entre mathématiques et musique.',
        notable_works: JSON.stringify(['Théorème de Pythagore', 'Table de Pythagore', 'Rapports harmoniques musicaux', 'Nombres figurés']),
        quotes: JSON.stringify(['Tout est nombre', 'Ne dis pas un petit nombre de choses en beaucoup de mots, mais beaucoup de choses en peu de mots', 'Éduquez les enfants et il ne sera pas nécessaire de punir les hommes']),
        era: 'antiquite',
        historical_importance: 'Pythagore a établi les mathématiques comme discipline fondamentale de la compréhension du monde. Son théorème reste enseigné dans toutes les écoles du monde. Sa vision des nombres comme essence de la réalité a profondément influencé la physique mathématique moderne.',
        anecdote: 'Pythagore et ses disciples avaient des règles de vie très strictes : ils ne mangeaient pas de fèves (peut-être par superstition ou pour des raisons médicales liées au favisme). Selon la légende, poursuivi par ses ennemis, Pythagore aurait préféré se laisser capturer plutôt que de traverser un champ de fèves pour s\'enfuir.',
      },
      {
        slug: 'euclide',
        first_name: 'Euclide',
        last_name: '',
        full_name: 'Euclide',
        birth_date: '325 av. J.-C.',
        death_date: '265 av. J.-C.',
        birth_place: 'Alexandrie, Égypte',
        death_place: 'Alexandrie, Égypte',
        nationality: 'Grecque',
        category: 'scientist',
        subcategory: 'Mathématicien',
        summary: 'Père de la géométrie, auteur des Éléments, le livre le plus influent de l\'histoire des mathématiques.',
        biography_text: 'Euclide enseigne les mathématiques à Alexandrie sous le règne de Ptolémée Ier. Ses Éléments, en 13 livres, organisent de manière logique et déductive l\'ensemble des connaissances géométriques de l\'Antiquité. À partir d\'un petit nombre d\'axiomes et de postulats, il démontre rigoureusement des centaines de théorèmes. Ce modèle de raisonnement déductif a influencé toute la pensée scientifique occidentale pendant plus de 2 000 ans.',
        notable_works: JSON.stringify(['Les Éléments (13 livres)', 'Les Données', 'L\'Optique', 'Les Coniques']),
        quotes: JSON.stringify(['Il n\'y a pas de chemin royal vers la géométrie', 'Ce qui est affirmé sans preuve peut être nié sans preuve']),
        era: 'antiquite',
        historical_importance: 'Les Éléments d\'Euclide sont le deuxième livre le plus imprimé de l\'histoire après la Bible. Son système axiomatique est devenu le modèle de toute démonstration mathématique et scientifique rigoureuse. La géométrie euclidienne reste la base de l\'enseignement mathématique mondial.',
        anecdote: 'Quand le roi Ptolémée Ier demanda à Euclide s\'il existait un moyen plus facile d\'apprendre la géométrie que de lire les Éléments, Euclide lui répondit : « Il n\'y a pas de chemin royal vers la géométrie », signifiant que même un roi devait faire l\'effort d\'étudier.',
      },
      {
        slug: 'al-khwarizmi',
        first_name: 'Muhammad ibn Musa',
        last_name: 'al-Khwarizmi',
        full_name: 'Al-Khwarizmi',
        birth_date: '780',
        death_date: '850',
        birth_place: 'Khwarezm, Ouzbékistan actuel',
        death_place: 'Bagdad, Irak',
        nationality: 'Perse',
        category: 'scientist',
        subcategory: 'Mathématicien',
        summary: 'Père de l\'algèbre, introducteur du système décimal et des chiffres arabes en Occident.',
        biography_text: 'Al-Khwarizmi travaille à la Maison de la Sagesse à Bagdad, le plus grand centre intellectuel du monde islamique médiéval. Son traité « Al-Kitab al-mukhtasar fi hisab al-jabr wal-muqabala » donne son nom à l\'algèbre (al-jabr). Il introduit les méthodes systématiques de résolution des équations du premier et second degré. Son nom latinisé, « Algoritmi », est à l\'origine du mot « algorithme ».',
        notable_works: JSON.stringify(['Al-jabr (traité d\'algèbre)', 'Algorithme de calcul décimal', 'Tables astronomiques (Zij)', 'Traité de géographie']),
        quotes: JSON.stringify(['Ce que j\'ai voulu, c\'est rendre plus facile et plus clair ce qui est difficile et obscur dans le calcul']),
        era: 'moyen_age',
        historical_importance: 'Al-Khwarizmi a donné son nom à deux concepts fondamentaux des mathématiques et de l\'informatique : l\'algèbre et l\'algorithme. Sa transmission des chiffres indo-arabes à l\'Occident a révolutionné le calcul et rendu possible le développement scientifique européen.',
        anecdote: 'Les mots « algèbre » et « algorithme » viennent tous deux d\'Al-Khwarizmi : « algèbre » du titre de son livre (al-jabr signifie « restauration » ou « complétion »), et « algorithme » de la latinisation de son nom. Sans lui, notre façon de faire des mathématiques serait radicalement différente.',
      },

      // ═══════════════════════════════════════════════════════════════
      // ÉCRIVAINS
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'voltaire',
        first_name: 'François-Marie',
        last_name: 'Arouet',
        full_name: 'Voltaire',
        birth_date: '21 novembre 1694',
        death_date: '30 mai 1778',
        birth_place: 'Paris, France',
        death_place: 'Paris, France',
        nationality: 'Française',
        category: 'writer',
        subcategory: 'Philosophe des Lumières',
        summary: 'Philosophe des Lumières, écrivain et polémiste, défenseur de la tolérance et de la liberté.',
        biography_text: 'Voltaire, de son vrai nom François-Marie Arouet, est l\'une des figures majeures des Lumières françaises. Emprisonné à la Bastille, exilé en Angleterre, il ne cesse de combattre l\'intolérance, le fanatisme et l\'injustice. Son œuvre immense comprend des tragédies, des contes philosophiques, des essais historiques et une correspondance monumentale. Son combat pour la liberté d\'expression influence profondément la Révolution française.',
        notable_works: JSON.stringify(['Candide', 'Lettres philosophiques', 'Traité sur la tolérance', 'Dictionnaire philosophique', 'Zadig']),
        quotes: JSON.stringify(['Je ne suis pas d\'accord avec ce que vous dites, mais je me battrai jusqu\'à la mort pour que vous ayez le droit de le dire', 'Le doute est inconfortable, la certitude est ridicule', 'Il faut cultiver notre jardin']),
        era: 'temps_modernes',
        historical_importance: 'Voltaire est le symbole des Lumières et de la lutte pour la tolérance et la liberté d\'expression. Son œuvre a directement inspiré la Déclaration des droits de l\'homme et la Révolution française. Il a inventé la figure de l\'intellectuel engagé dans les combats de société.',
        anecdote: 'Voltaire buvait entre 40 et 50 tasses de café par jour, un mélange de café et de chocolat. Quand on lui a dit que le café était un poison lent, il a répondu : « Je crois que vous avez raison. Il y a soixante ans que j\'en bois et je ne suis pas encore mort. »',
      },
      {
        slug: 'victor-hugo',
        first_name: 'Victor',
        last_name: 'Hugo',
        full_name: 'Victor Hugo',
        birth_date: '26 février 1802',
        death_date: '22 mai 1885',
        birth_place: 'Besançon, France',
        death_place: 'Paris, France',
        nationality: 'Française',
        category: 'writer',
        subcategory: 'Romancier, poète, dramaturge',
        summary: 'Écrivain majeur du XIXe siècle, chef de file du romantisme, engagé pour la justice sociale.',
        biography_text: 'Victor Hugo domine la littérature française du XIXe siècle. Poète, romancier, dramaturge et homme politique, il est le chef de file du romantisme. Ses romans (Les Misérables, Notre-Dame de Paris) dénoncent la misère et l\'injustice. Opposé au coup d\'État de Napoléon III, il s\'exile pendant 19 ans. Sénateur de la République, il milite pour l\'abolition de la peine de mort et les droits des enfants.',
        notable_works: JSON.stringify(['Les Misérables', 'Notre-Dame de Paris', 'Les Contemplations', 'Hernani', 'Les Châtiments']),
        quotes: JSON.stringify(['Ceux qui vivent, ce sont ceux qui luttent', 'La liberté commence où l\'ignorance finit', 'Rien n\'est plus fort qu\'une idée dont l\'heure est venue']),
        era: 'epoque_contemporaine',
        historical_importance: 'Hugo a transformé la littérature française avec le romantisme. Ses combats pour l\'abolition de la peine de mort, les droits des pauvres et l\'instruction publique gratuite ont façonné les valeurs républicaines françaises. Ses funérailles nationales en 1885 ont rassemblé deux millions de personnes.',
        anecdote: 'Victor Hugo communiquait avec son éditeur en utilisant le télégramme le plus court de l\'histoire. Après la publication des Misérables, il envoya « ? » à son éditeur pour connaître les ventes. L\'éditeur répondit « ! ». Le roman était un immense succès.',
      },
      {
        slug: 'william-shakespeare',
        first_name: 'William',
        last_name: 'Shakespeare',
        full_name: 'William Shakespeare',
        birth_date: '26 avril 1564',
        death_date: '23 avril 1616',
        birth_place: 'Stratford-upon-Avon, Angleterre',
        death_place: 'Stratford-upon-Avon, Angleterre',
        nationality: 'Anglaise',
        category: 'writer',
        subcategory: 'Dramaturge, poète',
        summary: 'Plus grand dramaturge de la langue anglaise, auteur d\'œuvres universelles du théâtre mondial.',
        biography_text: 'William Shakespeare est considéré comme le plus grand écrivain de langue anglaise. Acteur et dramaturge au Globe Theatre de Londres, il écrit 37 pièces de théâtre, 154 sonnets et plusieurs poèmes narratifs. Ses tragédies (Hamlet, Othello, Macbeth, Le Roi Lear) et comédies (Le Songe d\'une nuit d\'été, Beaucoup de bruit pour rien) explorent toute la gamme des émotions humaines avec une profondeur inégalée.',
        notable_works: JSON.stringify(['Hamlet', 'Roméo et Juliette', 'Macbeth', 'Othello', 'Le Songe d\'une nuit d\'été', 'Le Roi Lear']),
        quotes: JSON.stringify(['Être ou ne pas être, telle est la question', 'Le monde entier est un théâtre', 'L\'enfer est vide, tous les démons sont ici']),
        era: 'temps_modernes',
        historical_importance: 'Shakespeare a inventé ou popularisé plus de 1 700 mots anglais encore utilisés aujourd\'hui. Ses pièces sont jouées et étudiées dans le monde entier depuis quatre siècles. Il a porté l\'exploration psychologique des personnages à un niveau sans précédent.',
        anecdote: 'Shakespeare a inventé des mots que nous utilisons encore quotidiennement en anglais : « eyeball » (globe oculaire), « bedroom » (chambre), « lonely » (solitaire), « generous » (généreux). On estime qu\'il a introduit environ 1 700 mots dans la langue anglaise.',
      },

      // ═══════════════════════════════════════════════════════════════
      // PEINTRES
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'leonard-de-vinci',
        first_name: 'Léonard',
        last_name: 'de Vinci',
        full_name: 'Léonard de Vinci',
        birth_date: '15 avril 1452',
        death_date: '2 mai 1519',
        birth_place: 'Vinci, Italie',
        death_place: 'Amboise, France',
        nationality: 'Italienne',
        category: 'artist',
        subcategory: 'Peintre',
        summary: 'Génie universel de la Renaissance, peintre, sculpteur, architecte, ingénieur et scientifique.',
        biography_text: 'Léonard de Vinci incarne l\'idéal de l\'homme de la Renaissance. Formé dans l\'atelier de Verrocchio à Florence, il devient l\'un des plus grands artistes de l\'histoire. Au-delà de la peinture, il s\'intéresse à l\'anatomie, l\'ingénierie, la botanique, la géologie et l\'aéronautique. Ses carnets contiennent des milliers de croquis et d\'inventions visionnaires. Il passe ses dernières années en France, invité par François Ier.',
        notable_works: JSON.stringify(['La Joconde', 'La Cène', 'L\'Homme de Vitruve', 'La Vierge aux rochers', 'La Dame à l\'hermine']),
        quotes: JSON.stringify(['La simplicité est la sophistication suprême', 'Apprendre ne fatigue jamais l\'esprit', 'Les détails font la perfection, et la perfection n\'est pas un détail']),
        era: 'renaissance',
        historical_importance: 'Léonard de Vinci est le symbole même du génie universel. Il a révolutionné la peinture avec le sfumato et la perspective atmosphérique. Ses études anatomiques ont avancé la médecine. Ses inventions préfigurent l\'hélicoptère, le char d\'assaut et le parachute, des siècles avant leur réalisation.',
        anecdote: 'Léonard de Vinci écrivait en miroir, de droite à gauche. Pour lire ses carnets, il faut un miroir. On ne sait pas s\'il le faisait pour protéger ses idées, parce qu\'il était gaucher (pour ne pas étaler l\'encre), ou simplement par habitude.',
      },
      {
        slug: 'michel-ange',
        first_name: 'Michelangelo',
        last_name: 'Buonarroti',
        full_name: 'Michel-Ange',
        birth_date: '6 mars 1475',
        death_date: '18 février 1564',
        birth_place: 'Caprese, Italie',
        death_place: 'Rome, Italie',
        nationality: 'Italienne',
        category: 'artist',
        subcategory: 'Peintre, sculpteur',
        summary: 'Sculpteur, peintre et architecte de la Renaissance, créateur du plafond de la chapelle Sixtine.',
        biography_text: 'Michel-Ange est l\'un des artistes les plus complets de l\'histoire. Sculpteur, il crée le David et la Pietà, chefs-d\'œuvre de la sculpture mondiale. Peintre, il réalise les fresques de la chapelle Sixtine, dont La Création d\'Adam. Architecte, il conçoit le dôme de la basilique Saint-Pierre de Rome. Son art exprime une puissance émotionnelle et une maîtrise technique inégalées qui influenceront l\'art pendant des siècles.',
        notable_works: JSON.stringify(['David', 'Pietà', 'Plafond de la chapelle Sixtine', 'Le Jugement dernier', 'Dôme de Saint-Pierre de Rome']),
        quotes: JSON.stringify(['J\'ai vu un ange dans le marbre et j\'ai sculpté jusqu\'à le libérer', 'Le plus grand danger n\'est pas de viser trop haut et de manquer la cible, mais de viser trop bas et de l\'atteindre']),
        era: 'renaissance',
        historical_importance: 'Michel-Ange a redéfini les canons de la beauté et de l\'art occidental. Le plafond de la chapelle Sixtine est considéré comme l\'une des plus grandes réalisations artistiques de l\'humanité. Son David est devenu le symbole de Florence et de la perfection sculpturale.',
        anecdote: 'Michel-Ange a peint le plafond de la chapelle Sixtine en quatre ans (1508-1512), couché sur un échafaudage à 20 mètres de hauteur. Contrairement à la croyance populaire, il ne peignait pas allongé sur le dos mais debout, la tête renversée en arrière. Cette position lui a causé des déformations permanentes de la colonne vertébrale.',
      },
      {
        slug: 'pablo-picasso',
        first_name: 'Pablo',
        last_name: 'Picasso',
        full_name: 'Pablo Picasso',
        birth_date: '25 octobre 1881',
        death_date: '8 avril 1973',
        birth_place: 'Málaga, Espagne',
        death_place: 'Mougins, France',
        nationality: 'Espagnole',
        category: 'artist',
        subcategory: 'Peintre',
        summary: 'Co-fondateur du cubisme, l\'un des artistes les plus influents du XXe siècle.',
        biography_text: 'Pablo Picasso domine l\'art du XXe siècle. Prodige dès l\'enfance, il traverse de nombreuses périodes artistiques : période bleue, période rose, cubisme, néoclassicisme, surréalisme. Avec Georges Braque, il invente le cubisme en 1907 avec Les Demoiselles d\'Avignon, révolutionnant la représentation visuelle. Son tableau Guernica (1937), dénonçant le bombardement de la ville basque, est devenu un symbole universel de l\'horreur de la guerre.',
        notable_works: JSON.stringify(['Guernica', 'Les Demoiselles d\'Avignon', 'La Femme qui pleure', 'Le Vieux Guitariste aveugle', 'Les Ménines (d\'après Vélasquez)']),
        quotes: JSON.stringify(['Tout enfant est un artiste. Le problème est de rester artiste en grandissant', 'J\'ai mis toute ma vie à savoir dessiner comme un enfant', 'L\'art est un mensonge qui nous fait réaliser la vérité']),
        era: 'epoque_contemporaine',
        historical_importance: 'Picasso a révolutionné l\'art moderne en brisant les conventions de la représentation visuelle. Le cubisme a ouvert la voie à l\'art abstrait et à toutes les avant-gardes du XXe siècle. Guernica reste le tableau anti-guerre le plus puissant jamais peint.',
        anecdote: 'Le nom complet de Picasso est Pablo Diego José Francisco de Paula Juan Nepomuceno Crispín Crispiniano María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso. C\'est l\'un des noms les plus longs jamais portés, composé des noms de divers saints et parents.',
      },

      // ═══════════════════════════════════════════════════════════════
      // MUSICIENS
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'wolfgang-amadeus-mozart',
        first_name: 'Wolfgang Amadeus',
        last_name: 'Mozart',
        full_name: 'Wolfgang Amadeus Mozart',
        birth_date: '27 janvier 1756',
        death_date: '5 décembre 1791',
        birth_place: 'Salzbourg, Autriche',
        death_place: 'Vienne, Autriche',
        nationality: 'Autrichienne',
        category: 'musician',
        subcategory: 'Compositeur classique',
        summary: 'Compositeur prodige de l\'époque classique, l\'un des plus grands musiciens de l\'histoire.',
        biography_text: 'Mozart montre des dons musicaux exceptionnels dès l\'âge de 3 ans. Son père Léopold l\'exhibe dans les cours européennes. Il compose son premier opéra à 12 ans. Son œuvre couvre tous les genres : opéras (Don Giovanni, Les Noces de Figaro, La Flûte enchantée), symphonies, concertos, musique de chambre. Malgré une vie brève (35 ans), il laisse plus de 600 œuvres qui définissent le classicisme musical.',
        notable_works: JSON.stringify(['La Flûte enchantée', 'Don Giovanni', 'Requiem', 'Les Noces de Figaro', 'Symphonie n°40', 'Petite musique de nuit']),
        quotes: JSON.stringify(['La musique n\'est pas dans les notes, mais dans le silence entre les notes', 'Ni trop haut, ni trop bas : la vérité est dans la nuance']),
        era: 'temps_modernes',
        historical_importance: 'Mozart a porté la musique classique à son apogée. Ses opéras ont redéfini le genre lyrique. Son Requiem inachevé reste l\'un des morceaux les plus émouvants jamais composés. Il a influencé tous les compositeurs qui l\'ont suivi, de Beethoven à Tchaïkovski.',
        anecdote: 'Mozart avait un sens de l\'humour très particulier. Dans ses lettres à sa famille, il utilisait un langage scatologique et des jeux de mots grossiers. Il a aussi composé un canon intitulé « Leck mich im Arsch » (traduction polie impossible), démontrant qu\'un génie musical peut aussi être très irrévérencieux.',
      },
      {
        slug: 'ludwig-van-beethoven',
        first_name: 'Ludwig van',
        last_name: 'Beethoven',
        full_name: 'Ludwig van Beethoven',
        birth_date: '17 décembre 1770',
        death_date: '26 mars 1827',
        birth_place: 'Bonn, Allemagne',
        death_place: 'Vienne, Autriche',
        nationality: 'Allemande',
        category: 'musician',
        subcategory: 'Compositeur romantique',
        summary: 'Compositeur et pianiste, figure de transition entre classicisme et romantisme, génie malgré la surdité.',
        biography_text: 'Beethoven est l\'un des compositeurs les plus admirés de l\'histoire. Formé dans la tradition classique de Haydn, il développe un style révolutionnaire qui annonce le romantisme. Ses 9 symphonies, 32 sonates pour piano et ses concertos repoussent les limites de la musique. Frappé de surdité progressive dès l\'âge de 26 ans, il compose ses œuvres les plus monumentales alors qu\'il est complètement sourd, dont la Neuvième Symphonie avec l\'Ode à la Joie.',
        notable_works: JSON.stringify(['Symphonie n°5', 'Symphonie n°9 (Ode à la Joie)', 'Sonate au Clair de lune', 'Für Elise', 'Concerto pour piano n°5 (L\'Empereur)']),
        quotes: JSON.stringify(['La musique est une révélation plus haute que toute sagesse et toute philosophie', 'Je saisirai le destin à la gorge ; il ne me fera certainement pas plier']),
        era: 'epoque_contemporaine',
        historical_importance: 'Beethoven a transformé la musique d\'un divertissement aristocratique en un art d\'expression personnelle profonde. Sa Neuvième Symphonie est devenue l\'hymne européen. Il a prouvé que l\'art peut transcender les limites physiques : ses plus grandes œuvres ont été composées alors qu\'il était sourd.',
        anecdote: 'Beethoven, devenu sourd, dirigeait encore ses propres concerts. Lors de la première de la Neuvième Symphonie en 1824, il ne pouvait pas entendre les applaudissements du public. La contralto Caroline Unger dut le retourner face au public pour qu\'il voie l\'ovation debout que lui faisait la salle.',
      },
      {
        slug: 'jean-sebastien-bach',
        first_name: 'Jean-Sébastien',
        last_name: 'Bach',
        full_name: 'Jean-Sébastien Bach',
        birth_date: '31 mars 1685',
        death_date: '28 juillet 1750',
        birth_place: 'Eisenach, Allemagne',
        death_place: 'Leipzig, Allemagne',
        nationality: 'Allemande',
        category: 'musician',
        subcategory: 'Compositeur baroque',
        summary: 'Compositeur et organiste baroque, considéré comme le plus grand musicien de tous les temps par de nombreux experts.',
        biography_text: 'Jean-Sébastien Bach est issu d\'une famille de musiciens et sert comme Kantor à Leipzig pendant 27 ans. Son œuvre immense englobe tous les genres de la musique baroque sauf l\'opéra : cantates, passions, fugues, concertos, suites. Maître absolu du contrepoint et de l\'harmonie, il porte la musique baroque à son sommet. Relativement oublié après sa mort, il est redécouvert au XIXe siècle par Mendelssohn.',
        notable_works: JSON.stringify(['Le Clavier bien tempéré', 'Passion selon saint Matthieu', 'Concertos brandebourgeois', 'Messe en si mineur', 'L\'Art de la fugue', 'Toccata et fugue en ré mineur']),
        quotes: JSON.stringify(['Le but de la musique devrait être la gloire de Dieu et le délassement de l\'âme', 'Toute musique qui ne fait pas référence à la louange de Dieu n\'est rien qu\'un vain bruit']),
        era: 'temps_modernes',
        historical_importance: 'Bach est considéré comme le fondateur de toute la musique occidentale moderne. Le Clavier bien tempéré a établi le système tonal encore utilisé aujourd\'hui. Beethoven l\'appelait « le père de l\'harmonie ». Brahms a dit : « Si toute la musique qui a été écrite depuis Bach venait à être perdue, on pourrait la reconstruire sur la base de ce que Bach a écrit. »',
        anecdote: 'Bach a eu 20 enfants avec deux épouses. Quatre de ses fils sont devenus des compositeurs importants. Quand il est décédé, sa musique a été largement oubliée pendant 80 ans. C\'est Felix Mendelssohn qui a organisé en 1829 une exécution de la Passion selon saint Matthieu, relançant l\'intérêt pour Bach.',
      },

      // ═══════════════════════════════════════════════════════════════
      // EXPLORATEURS
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'christophe-colomb',
        first_name: 'Christophe',
        last_name: 'Colomb',
        full_name: 'Christophe Colomb',
        birth_date: '1451',
        death_date: '20 mai 1506',
        birth_place: 'Gênes, Italie',
        death_place: 'Valladolid, Espagne',
        nationality: 'Génoise / Espagnole',
        category: 'explorer',
        subcategory: 'Navigateur',
        summary: 'Navigateur génois au service de l\'Espagne, il atteint l\'Amérique en 1492.',
        biography_text: 'Christophe Colomb, convaincu de pouvoir atteindre l\'Asie en naviguant vers l\'ouest, obtient le soutien des rois catholiques d\'Espagne Ferdinand et Isabelle. Le 12 octobre 1492, il atteint les Bahamas, qu\'il croit être les Indes. Il effectue quatre voyages vers le « Nouveau Monde » sans jamais réaliser qu\'il a découvert un continent inconnu des Européens. Cette « découverte » transforme radicalement l\'histoire mondiale.',
        notable_works: JSON.stringify(['Découverte des Amériques (1492)', 'Quatre voyages transatlantiques', 'Établissement de la route atlantique', 'Journal de bord']),
        quotes: JSON.stringify(['Vous ne pouvez jamais traverser l\'océan tant que vous n\'avez pas le courage de perdre de vue le rivage', 'L\'or est un trésor, et celui qui le possède fait tout ce qu\'il veut dans le monde']),
        era: 'renaissance',
        historical_importance: 'La « découverte » de l\'Amérique par Colomb en 1492 est l\'un des événements les plus marquants de l\'histoire. Elle a initié l\'échange colombien (transfert de plantes, animaux, maladies et cultures entre l\'Ancien et le Nouveau Monde), la colonisation des Amériques et la mondialisation.',
        anecdote: 'Colomb n\'a jamais su qu\'il avait découvert un nouveau continent. Jusqu\'à sa mort, il était convaincu d\'avoir atteint l\'Asie. C\'est Amerigo Vespucci, un autre explorateur italien, qui a compris qu\'il s\'agissait d\'un « Nouveau Monde », et c\'est son prénom qui a donné le nom « Amérique » au continent.',
      },
      {
        slug: 'marco-polo',
        first_name: 'Marco',
        last_name: 'Polo',
        full_name: 'Marco Polo',
        birth_date: '15 septembre 1254',
        death_date: '8 janvier 1324',
        birth_place: 'Venise, Italie',
        death_place: 'Venise, Italie',
        nationality: 'Vénitienne',
        category: 'explorer',
        subcategory: 'Voyageur',
        summary: 'Marchand et voyageur vénitien, son récit de voyage en Chine a fasciné l\'Europe.',
        biography_text: 'Marco Polo part à 17 ans avec son père et son oncle pour un voyage de 24 ans en Asie. Il séjourne à la cour de l\'empereur mongol Koubilaï Khan pendant 17 ans, où il occupe des fonctions diplomatiques. De retour à Venise, il dicte ses mémoires en prison : « Le Devisement du monde » (ou « Il Milione ») décrit les merveilles de la Chine, du Japon et de l\'Asie du Sud-Est, ouvrant les yeux de l\'Europe sur l\'Orient.',
        notable_works: JSON.stringify(['Le Devisement du monde (Il Milione)', 'Route de la soie (parcours)', 'Descriptions de la Chine et de l\'Asie']),
        quotes: JSON.stringify(['Je n\'ai pas raconté la moitié de ce que j\'ai vu']),
        era: 'moyen_age',
        historical_importance: 'Le récit de Marco Polo a transformé la vision européenne du monde. Il a inspiré des générations d\'explorateurs, dont Christophe Colomb qui possédait un exemplaire annoté du Devisement du monde. Il a ouvert l\'imaginaire européen aux richesses et aux civilisations de l\'Orient.',
        anecdote: 'Sur son lit de mort, ses proches demandèrent à Marco Polo de retirer les « exagérations » de son livre. Il répondit : « Je n\'ai pas raconté la moitié de ce que j\'ai vu. » Longtemps considéré comme un affabulateur, la plupart de ses descriptions se sont révélées exactes.',
      },
      {
        slug: 'fernand-de-magellan',
        first_name: 'Fernand',
        last_name: 'de Magellan',
        full_name: 'Fernand de Magellan',
        birth_date: '1480',
        death_date: '27 avril 1521',
        birth_place: 'Sabrosa, Portugal',
        death_place: 'Mactan, Philippines',
        nationality: 'Portugaise',
        category: 'explorer',
        subcategory: 'Navigateur',
        summary: 'Navigateur portugais au service de l\'Espagne, initiateur du premier tour du monde.',
        biography_text: 'Fernand de Magellan conçoit le projet audacieux de rejoindre les Moluques (îles aux épices) en contournant l\'Amérique du Sud par le sud. Il quitte l\'Espagne en 1519 avec 5 navires et 237 hommes. Il découvre le détroit qui porte son nom, traverse l\'océan Pacifique (qu\'il baptise ainsi en raison de son calme apparent) et atteint les Philippines, où il est tué lors d\'un combat. Juan Sebastián Elcano termine le voyage en 1522 avec un seul navire et 18 survivants.',
        notable_works: JSON.stringify(['Première circumnavigation du globe', 'Découverte du détroit de Magellan', 'Traversée du Pacifique', 'Preuve de la rotondité de la Terre']),
        quotes: JSON.stringify(['L\'Église dit que la Terre est plate, mais j\'ai vu l\'ombre sur la Lune et j\'ai plus confiance en une ombre qu\'en l\'Église']),
        era: 'renaissance',
        historical_importance: 'L\'expédition de Magellan a prouvé de manière irréfutable que la Terre est ronde et que les océans sont tous connectés. Cette première circumnavigation a révolutionné la cartographie et la navigation mondiale. Le détroit de Magellan est resté la principale route vers le Pacifique pendant des siècles.',
        anecdote: 'Sur les 237 hommes et 5 navires partis d\'Espagne en 1519, seuls 18 hommes et 1 navire (le Victoria) sont revenus en 1522. Magellan lui-même n\'a pas survécu au voyage : il a été tué par des guerriers philippins sur l\'île de Mactan. C\'est son lieutenant Elcano qui a achevé le premier tour du monde.',
      },

      // ═══════════════════════════════════════════════════════════════
      // DIRIGEANTS HISTORIQUES
      // ═══════════════════════════════════════════════════════════════
      {
        slug: 'napoleon-bonaparte',
        first_name: 'Napoléon',
        last_name: 'Bonaparte',
        full_name: 'Napoléon Bonaparte',
        birth_date: '15 août 1769',
        death_date: '5 mai 1821',
        birth_place: 'Ajaccio, Corse',
        death_place: 'Sainte-Hélène',
        nationality: 'Française',
        category: 'politician',
        subcategory: 'Dirigeant historique',
        summary: 'Empereur des Français, stratège militaire de génie et réformateur de l\'État moderne.',
        biography_text: 'Napoléon Bonaparte s\'impose comme général pendant la Révolution française, puis devient Premier consul (1799) et empereur (1804). Il modernise profondément la France : Code civil, système éducatif, Banque de France, préfets. Ses campagnes militaires redessinent la carte de l\'Europe. Vaincu à Waterloo (1815), il est exilé à Sainte-Hélène où il meurt en 1821.',
        notable_works: JSON.stringify(['Code civil', 'Code pénal', 'Création des lycées', 'Banque de France', 'Légion d\'honneur']),
        quotes: JSON.stringify(['Impossible n\'est pas français', 'Du sublime au ridicule, il n\'y a qu\'un pas', 'On ne conduit le peuple qu\'en lui montrant un avenir : un chef est un marchand d\'espérance']),
        era: 'epoque_contemporaine',
        historical_importance: 'Napoléon a modernisé la France et diffusé les idéaux de la Révolution en Europe. Le Code civil napoléonien est encore la base du droit dans de nombreux pays. Ses guerres ont redessiné la carte européenne et stimulé les mouvements nationalistes du XIXe siècle.',
        anecdote: 'Contrairement à la croyance populaire, Napoléon n\'était pas petit. Il mesurait environ 1,69 m, soit la taille moyenne d\'un Français de l\'époque. La confusion vient de la différence entre le pouce français et le pouce anglais, et de la propagande britannique qui le caricaturait en « petit caporal ».',
      },
      {
        slug: 'jules-cesar',
        first_name: 'Jules',
        last_name: 'César',
        full_name: 'Jules César',
        birth_date: '12 juillet 100 av. J.-C.',
        death_date: '15 mars 44 av. J.-C.',
        birth_place: 'Rome, Italie',
        death_place: 'Rome, Italie',
        nationality: 'Romaine',
        category: 'politician',
        subcategory: 'Dirigeant historique',
        summary: 'Général et homme d\'État romain, conquérant de la Gaule, dictateur de Rome.',
        biography_text: 'Caius Julius Caesar est l\'une des figures les plus marquantes de l\'Antiquité. Brillant orateur et stratège militaire, il conquiert la Gaule en huit ans (58-50 av. J.-C.), racontant ses campagnes dans « La Guerre des Gaules ». Après avoir franchi le Rubicon en 49 av. J.-C. et vaincu Pompée, il devient dictateur perpétuel de Rome. Ses réformes (calendrier julien, citoyenneté élargie, travaux publics) transforment Rome. Il est assassiné le 15 mars 44 av. J.-C. par un groupe de sénateurs.',
        notable_works: JSON.stringify(['La Guerre des Gaules', 'Réforme du calendrier (calendrier julien)', 'Conquête de la Gaule', 'Réformes politiques et sociales']),
        quotes: JSON.stringify(['Veni, vidi, vici (Je suis venu, j\'ai vu, j\'ai vaincu)', 'Alea jacta est (Le sort en est jeté)', 'Tu quoque, mi fili (Toi aussi, mon fils)']),
        era: 'antiquite',
        historical_importance: 'César a transformé la République romaine en Empire, changeant le cours de l\'histoire occidentale. Le calendrier julien qu\'il a instauré est resté en usage pendant 1 600 ans. La Guerre des Gaules est un document historique majeur sur les Celtes et la stratégie militaire antique.',
        anecdote: 'Le mois de juillet (July en anglais) porte le nom de Jules César. Quand les sénateurs l\'ont assassiné le 15 mars 44 av. J.-C. (les « Ides de Mars »), César aurait reçu 23 coups de poignard. Selon la tradition, en voyant Brutus parmi les assassins, il aurait dit : « Tu quoque, mi fili » (Toi aussi, mon fils).',
      },
      {
        slug: 'alexandre-le-grand',
        first_name: 'Alexandre',
        last_name: 'le Grand',
        full_name: 'Alexandre le Grand',
        birth_date: '21 juillet 356 av. J.-C.',
        death_date: '13 juin 323 av. J.-C.',
        birth_place: 'Pella, Macédoine',
        death_place: 'Babylone, Irak actuel',
        nationality: 'Macédonienne / Grecque',
        category: 'politician',
        subcategory: 'Dirigeant historique',
        summary: 'Roi de Macédoine, conquérant d\'un empire s\'étendant de la Grèce à l\'Inde.',
        biography_text: 'Alexandre III de Macédoine, élève d\'Aristote, succède à son père Philippe II à 20 ans. En seulement 13 ans, il conquiert le plus vaste empire de l\'Antiquité : Égypte, Perse, Asie centrale, jusqu\'aux rives de l\'Indus. Il fonde plus de 70 cités, dont Alexandrie d\'Égypte. Sa politique de fusion des cultures grecque et orientale crée la civilisation hellénistique. Il meurt à Babylone à 32 ans, probablement de fièvre.',
        notable_works: JSON.stringify(['Conquête de l\'Empire perse', 'Fondation d\'Alexandrie', 'Diffusion de la culture hellénistique', 'Plus de 70 cités fondées']),
        quotes: JSON.stringify(['Il n\'y a rien d\'impossible à celui qui ose', 'Je ne crains pas une armée de lions menée par un mouton. Je crains une armée de moutons menée par un lion']),
        era: 'antiquite',
        historical_importance: 'Alexandre a créé le monde hellénistique, fusionnant les cultures grecque et orientale. Cette synthèse culturelle a duré des siècles et a profondément influencé l\'art, la science et la philosophie. La bibliothèque d\'Alexandrie, qu\'il a fondée, est devenue le plus grand centre de savoir du monde antique.',
        anecdote: 'Le nœud gordien était un nœud légendaire réputé impossible à défaire. Quiconque le dénouerait régnerait sur l\'Asie. Alexandre, au lieu de chercher à le défaire, l\'a tranché d\'un coup d\'épée, inventant la solution radicale connue comme « trancher le nœud gordien ».',
      },
    ])
    .returning('*');

  // Contributions
  const socrate = persons.find((p: any) => p.slug === 'socrate');
  const vinci = persons.find((p: any) => p.slug === 'leonard-de-vinci');
  const curie = persons.find((p: any) => p.slug === 'marie-curie');
  const einstein = persons.find((p: any) => p.slug === 'albert-einstein');
  const newton = persons.find((p: any) => p.slug === 'isaac-newton');
  const descartes = persons.find((p: any) => p.slug === 'rene-descartes');
  const galilee = persons.find((p: any) => p.slug === 'galilee');
  const alkhwarizmi = persons.find((p: any) => p.slug === 'al-khwarizmi');
  const beethoven = persons.find((p: any) => p.slug === 'ludwig-van-beethoven');
  const colomb = persons.find((p: any) => p.slug === 'christophe-colomb');
  const cesar = persons.find((p: any) => p.slug === 'jules-cesar');

  await knex('person_contributions').insert([
    // Socrate
    { person_id: socrate.id, title: 'La maïeutique', description: 'Méthode de questionnement pour faire émerger la vérité', year: -430, domain: 'Philosophie' },
    { person_id: socrate.id, title: 'L\'éthique philosophique', description: 'Fondation de la réflexion morale systématique en Occident', year: -420, domain: 'Philosophie' },
    // Léonard de Vinci
    { person_id: vinci.id, title: 'La Joconde', description: 'Portrait le plus célèbre au monde, exposé au musée du Louvre', year: 1503, domain: 'Peinture' },
    { person_id: vinci.id, title: 'Études anatomiques', description: 'Dessins anatomiques d\'une précision inégalée pour l\'époque', year: 1489, domain: 'Science' },
    { person_id: vinci.id, title: 'Machines volantes', description: 'Conception de machines volantes préfigurant l\'aviation', year: 1485, domain: 'Ingénierie' },
    // Marie Curie
    { person_id: curie.id, title: 'Découverte du radium', description: 'Isolation du radium, élément radioactif aux applications médicales', year: 1898, domain: 'Chimie' },
    { person_id: curie.id, title: 'Prix Nobel de physique', description: 'Travaux sur la radioactivité, partagé avec Pierre Curie et Henri Becquerel', year: 1903, domain: 'Physique' },
    { person_id: curie.id, title: 'Prix Nobel de chimie', description: 'Découverte du radium et du polonium', year: 1911, domain: 'Chimie' },
    // Einstein
    { person_id: einstein.id, title: 'Relativité restreinte', description: 'Théorie unissant espace et temps, aboutissant à E=mc²', year: 1905, domain: 'Physique' },
    { person_id: einstein.id, title: 'Relativité générale', description: 'Nouvelle théorie de la gravitation remplaçant celle de Newton', year: 1915, domain: 'Physique' },
    { person_id: einstein.id, title: 'Effet photoélectrique', description: 'Explication quantique de l\'émission d\'électrons par la lumière (Nobel 1921)', year: 1905, domain: 'Physique' },
    // Newton
    { person_id: newton.id, title: 'Loi de la gravitation universelle', description: 'Unification de la mécanique terrestre et céleste', year: 1687, domain: 'Physique' },
    { person_id: newton.id, title: 'Lois du mouvement', description: 'Trois lois fondamentales régissant le mouvement des objets', year: 1687, domain: 'Physique' },
    { person_id: newton.id, title: 'Calcul infinitésimal', description: 'Co-invention (avec Leibniz) du calcul différentiel et intégral', year: 1666, domain: 'Mathématiques' },
    { person_id: newton.id, title: 'Décomposition de la lumière', description: 'Démonstration que la lumière blanche est composée de toutes les couleurs', year: 1672, domain: 'Optique' },
    // Descartes
    { person_id: descartes.id, title: 'Géométrie analytique', description: 'Union de l\'algèbre et de la géométrie par les coordonnées cartésiennes', year: 1637, domain: 'Mathématiques' },
    { person_id: descartes.id, title: 'Doute méthodique', description: 'Méthode philosophique fondée sur le doute systématique', year: 1637, domain: 'Philosophie' },
    // Galilée
    { person_id: galilee.id, title: 'Lois de la chute des corps', description: 'Démonstration que tous les objets tombent à la même vitesse', year: 1590, domain: 'Physique' },
    { person_id: galilee.id, title: 'Observations astronomiques', description: 'Découverte des satellites de Jupiter et des phases de Vénus', year: 1610, domain: 'Astronomie' },
    // Al-Khwarizmi
    { person_id: alkhwarizmi.id, title: 'Fondation de l\'algèbre', description: 'Premier traité systématique de résolution des équations', year: 820, domain: 'Mathématiques' },
    { person_id: alkhwarizmi.id, title: 'Introduction des chiffres arabes', description: 'Transmission du système décimal positionnel à l\'Occident', year: 825, domain: 'Mathématiques' },
    // Beethoven
    { person_id: beethoven.id, title: 'Neuvième Symphonie', description: 'Première symphonie intégrant un chœur, devenue l\'hymne européen', year: 1824, domain: 'Musique' },
    { person_id: beethoven.id, title: 'Sonate au Clair de lune', description: 'L\'une des pièces pour piano les plus connues au monde', year: 1801, domain: 'Musique' },
    // Christophe Colomb
    { person_id: colomb.id, title: 'Découverte de l\'Amérique', description: 'Premier contact européen durable avec le Nouveau Monde', year: 1492, domain: 'Exploration' },
    // Jules César
    { person_id: cesar.id, title: 'Conquête de la Gaule', description: 'Conquête et romanisation de la Gaule en 8 ans', year: -52, domain: 'Militaire' },
    { person_id: cesar.id, title: 'Calendrier julien', description: 'Réforme du calendrier romain, base du calendrier moderne', year: -46, domain: 'Administration' },
  ]);
}
