import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('person_contributions').del();
  await knex('persons').del();

  const persons = await knex('persons')
    .insert([
      {
        slug: 'socrate',
        first_name: 'Socrate',
        last_name: '',
        full_name: 'Socrate',
        birth_date: '470 av. J.-C.',
        death_date: '399 av. J.-C.',
        birth_place: 'Athènes, Grèce',
        death_place: 'Athènes, Grèce',
        nationality: 'Grecque',
        category: 'philosopher',
        subcategory: 'Philosophie antique',
        summary: 'Philosophe grec fondateur de la philosophie occidentale, connu pour sa méthode de questionnement (maïeutique).',
        biography_text: 'Socrate est considéré comme le père de la philosophie occidentale. Il n\'a laissé aucun écrit, et sa pensée nous est parvenue à travers les dialogues de son élève Platon. Sa méthode, la maïeutique, consiste à faire « accoucher » les esprits de leurs connaissances par le questionnement. Accusé de corrompre la jeunesse et de ne pas reconnaître les dieux de la cité, il est condamné à mort et boit la ciguë en 399 av. J.-C.',
        notable_works: JSON.stringify(['Méthode maïeutique', 'Dialogues socratiques (via Platon)']),
        quotes: JSON.stringify(['Je sais que je ne sais rien', 'Connais-toi toi-même', 'Une vie sans examen ne vaut pas la peine d\'être vécue']),
        era: 'antiquite',
      },
      {
        slug: 'leonard-de-vinci',
        first_name: 'Léonard',
        last_name: 'de Vinci',
        full_name: 'Léonard de Vinci',
        birth_date: '15 avril 1452',
        death_date: '2 mai 1519',
        birth_place: 'Vinci, Italie',
        death_place: 'Amboise, France',
        nationality: 'Italienne',
        category: 'artist',
        subcategory: 'Peinture, ingénierie',
        summary: 'Génie universel de la Renaissance, peintre, sculpteur, architecte, ingénieur et scientifique.',
        biography_text: 'Léonard de Vinci incarne l\'idéal de l\'homme de la Renaissance. Formé dans l\'atelier de Verrocchio à Florence, il devient l\'un des plus grands artistes de l\'histoire. Au-delà de la peinture, il s\'intéresse à l\'anatomie, l\'ingénierie, la botanique, la géologie et l\'aéronautique. Ses carnets contiennent des milliers de croquis et d\'inventions visionnaires. Il passe ses dernières années en France, invité par François Ier.',
        notable_works: JSON.stringify(['La Joconde', 'La Cène', 'L\'Homme de Vitruve', 'Codex Atlanticus']),
        quotes: JSON.stringify(['La simplicité est la sophistication suprême', 'Apprendre ne fatigue jamais l\'esprit']),
        era: 'renaissance',
      },
      {
        slug: 'marie-curie',
        first_name: 'Marie',
        last_name: 'Curie',
        full_name: 'Marie Curie',
        birth_date: '7 novembre 1867',
        death_date: '4 juillet 1934',
        birth_place: 'Varsovie, Pologne',
        death_place: 'Passy, France',
        nationality: 'Polonaise / Française',
        category: 'scientist',
        subcategory: 'Physique, chimie',
        summary: 'Première femme à recevoir un prix Nobel, pionnière de la recherche sur la radioactivité.',
        biography_text: 'Maria Sklodowska, devenue Marie Curie, quitte la Pologne pour étudier à Paris. Avec son mari Pierre Curie, elle découvre le polonium et le radium. Elle est la première femme professeure à la Sorbonne et la seule personne à avoir reçu des prix Nobel dans deux disciplines scientifiques différentes (physique en 1903, chimie en 1911). Ses travaux sur la radioactivité ont révolutionné la physique et la médecine.',
        notable_works: JSON.stringify(['Découverte du polonium', 'Découverte du radium', 'Recherches sur la radioactivité']),
        quotes: JSON.stringify(['Dans la vie, rien n\'est à craindre, tout est à comprendre', 'On ne fait jamais attention à ce qui a été fait ; on ne voit que ce qui reste à faire']),
        era: 'epoque_contemporaine',
      },
      {
        slug: 'napoleon-bonaparte',
        first_name: 'Napoléon',
        last_name: 'Bonaparte',
        full_name: 'Napoléon Bonaparte',
        birth_date: '15 août 1769',
        death_date: '5 mai 1821',
        birth_place: 'Ajaccio, Corse',
        death_place: 'Sainte-Hélène',
        nationality: 'Française',
        category: 'politician',
        subcategory: 'Chef d\'État, stratège militaire',
        summary: 'Empereur des Français, stratège militaire de génie et réformateur de l\'État moderne.',
        biography_text: 'Napoléon Bonaparte s\'impose comme général pendant la Révolution française, puis devient Premier consul (1799) et empereur (1804). Il modernise profondément la France : Code civil, système éducatif, Banque de France, préfets. Ses campagnes militaires redessinent la carte de l\'Europe. Vaincu à Waterloo (1815), il est exilé à Sainte-Hélène où il meurt en 1821.',
        notable_works: JSON.stringify(['Code civil', 'Code pénal', 'Création des lycées', 'Banque de France', 'Légion d\'honneur']),
        quotes: JSON.stringify(['Impossible n\'est pas français', 'Du sublime au ridicule, il n\'y a qu\'un pas']),
        era: 'epoque_contemporaine',
      },
      {
        slug: 'voltaire',
        first_name: 'François-Marie',
        last_name: 'Arouet',
        full_name: 'Voltaire',
        birth_date: '21 novembre 1694',
        death_date: '30 mai 1778',
        birth_place: 'Paris, France',
        death_place: 'Paris, France',
        nationality: 'Française',
        category: 'writer',
        subcategory: 'Philosophe des Lumières, écrivain',
        summary: 'Philosophe des Lumières, écrivain et polémiste, défenseur de la tolérance et de la liberté.',
        biography_text: 'Voltaire, de son vrai nom François-Marie Arouet, est l\'une des figures majeures des Lumières françaises. Emprisonné à la Bastille, exilé en Angleterre, il ne cesse de combattre l\'intolérance, le fanatisme et l\'injustice. Son œuvre immense comprend des tragédies, des contes philosophiques, des essais historiques et une correspondance monumentale. Son combat pour la liberté d\'expression influence profondément la Révolution française.',
        notable_works: JSON.stringify(['Candide', 'Lettres philosophiques', 'Traité sur la tolérance', 'Dictionnaire philosophique']),
        quotes: JSON.stringify(['Je ne suis pas d\'accord avec ce que vous dites, mais je me battrai jusqu\'à la mort pour que vous ayez le droit de le dire', 'Le doute est inconfortable, la certitude est ridicule']),
        era: 'temps_modernes',
      },
      {
        slug: 'wolfgang-amadeus-mozart',
        first_name: 'Wolfgang Amadeus',
        last_name: 'Mozart',
        full_name: 'Wolfgang Amadeus Mozart',
        birth_date: '27 janvier 1756',
        death_date: '5 décembre 1791',
        birth_place: 'Salzbourg, Autriche',
        death_place: 'Vienne, Autriche',
        nationality: 'Autrichienne',
        category: 'musician',
        subcategory: 'Compositeur classique',
        summary: 'Compositeur prodige de l\'époque classique, l\'un des plus grands musiciens de l\'histoire.',
        biography_text: 'Mozart montre des dons musicaux exceptionnels dès l\'âge de 3 ans. Son père Léopold l\'exhibe dans les cours européennes. Il compose son premier opéra à 12 ans. Son œuvre couvre tous les genres : opéras (Don Giovanni, Les Noces de Figaro, La Flûte enchantée), symphonies, concertos, musique de chambre. Malgré une vie brève (35 ans), il laisse plus de 600 œuvres qui définissent le classicisme musical.',
        notable_works: JSON.stringify(['La Flûte enchantée', 'Don Giovanni', 'Requiem', 'Les Noces de Figaro', 'Symphonie n°40']),
        quotes: JSON.stringify(['La musique n\'est pas dans les notes, mais dans le silence entre les notes']),
        era: 'temps_modernes',
      },
      {
        slug: 'albert-einstein',
        first_name: 'Albert',
        last_name: 'Einstein',
        full_name: 'Albert Einstein',
        birth_date: '14 mars 1879',
        death_date: '18 avril 1955',
        birth_place: 'Ulm, Allemagne',
        death_place: 'Princeton, États-Unis',
        nationality: 'Allemande / Suisse / Américaine',
        category: 'scientist',
        subcategory: 'Physique théorique',
        summary: 'Physicien théoricien, auteur de la théorie de la relativité et prix Nobel de physique 1921.',
        biography_text: 'Albert Einstein révolutionne la physique au début du XXe siècle. En 1905, son « annus mirabilis », il publie quatre articles fondamentaux, dont la relativité restreinte et l\'explication de l\'effet photoélectrique (qui lui vaut le Nobel en 1921). En 1915, il formule la relativité générale, qui redéfinit notre compréhension de la gravité, de l\'espace et du temps. Fuyant le nazisme, il s\'installe aux États-Unis en 1933.',
        notable_works: JSON.stringify(['Relativité restreinte (E=mc²)', 'Relativité générale', 'Effet photoélectrique', 'Mouvement brownien']),
        quotes: JSON.stringify(['L\'imagination est plus importante que le savoir', 'La folie, c\'est de faire toujours la même chose et de s\'attendre à un résultat différent']),
        era: 'epoque_contemporaine',
      },
      {
        slug: 'victor-hugo',
        first_name: 'Victor',
        last_name: 'Hugo',
        full_name: 'Victor Hugo',
        birth_date: '26 février 1802',
        death_date: '22 mai 1885',
        birth_place: 'Besançon, France',
        death_place: 'Paris, France',
        nationality: 'Française',
        category: 'writer',
        subcategory: 'Romancier, poète, dramaturge',
        summary: 'Écrivain majeur du XIXe siècle, chef de file du romantisme, engagé pour la justice sociale.',
        biography_text: 'Victor Hugo domine la littérature française du XIXe siècle. Poète, romancier, dramaturge et homme politique, il est le chef de file du romantisme. Ses romans (Les Misérables, Notre-Dame de Paris) dénoncent la misère et l\'injustice. Opposé au coup d\'État de Napoléon III, il s\'exile pendant 19 ans. Sénateur de la République, il milite pour l\'abolition de la peine de mort et les droits des enfants.',
        notable_works: JSON.stringify(['Les Misérables', 'Notre-Dame de Paris', 'Les Contemplations', 'Hernani', 'Les Châtiments']),
        quotes: JSON.stringify(['Ceux qui vivent, ce sont ceux qui luttent', 'La liberté commence où l\'ignorance finit']),
        era: 'epoque_contemporaine',
      },
    ])
    .returning('*');

  // Contributions
  const socrate = persons.find((p: any) => p.slug === 'socrate');
  const vinci = persons.find((p: any) => p.slug === 'leonard-de-vinci');
  const curie = persons.find((p: any) => p.slug === 'marie-curie');
  const einstein = persons.find((p: any) => p.slug === 'albert-einstein');

  await knex('person_contributions').insert([
    { person_id: socrate.id, title: 'La maïeutique', description: 'Méthode de questionnement pour faire émerger la vérité', year: -430, domain: 'Philosophie' },
    { person_id: socrate.id, title: 'L\'éthique philosophique', description: 'Fondation de la réflexion morale systématique en Occident', year: -420, domain: 'Philosophie' },
    { person_id: vinci.id, title: 'La Joconde', description: 'Portrait le plus célèbre au monde, exposé au musée du Louvre', year: 1503, domain: 'Peinture' },
    { person_id: vinci.id, title: 'Études anatomiques', description: 'Dessins anatomiques d\'une précision inégalée pour l\'époque', year: 1489, domain: 'Science' },
    { person_id: vinci.id, title: 'Machines volantes', description: 'Conception de machines volantes préfigurant l\'aviation', year: 1485, domain: 'Ingénierie' },
    { person_id: curie.id, title: 'Découverte du radium', description: 'Isolation du radium, élément radioactif aux applications médicales', year: 1898, domain: 'Chimie' },
    { person_id: curie.id, title: 'Prix Nobel de physique', description: 'Travaux sur la radioactivité, partagé avec Pierre Curie et Henri Becquerel', year: 1903, domain: 'Physique' },
    { person_id: curie.id, title: 'Prix Nobel de chimie', description: 'Découverte du radium et du polonium', year: 1911, domain: 'Chimie' },
    { person_id: einstein.id, title: 'Relativité restreinte', description: 'Théorie unissant espace et temps, aboutissant à E=mc²', year: 1905, domain: 'Physique' },
    { person_id: einstein.id, title: 'Relativité générale', description: 'Nouvelle théorie de la gravitation remplaçant celle de Newton', year: 1915, domain: 'Physique' },
    { person_id: einstein.id, title: 'Effet photoélectrique', description: 'Explication quantique de l\'émission d\'électrons par la lumière', year: 1905, domain: 'Physique' },
  ]);
}
