import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('wars').del();
  await knex('historical_events').del();

  // Get period IDs
  const periods = await knex('historical_periods').select('id', 'slug');
  const getPeriodId = (slug: string) => {
    const p = periods.find((p: any) => p.slug === slug);
    return p?.id;
  };

  await knex('historical_events').insert([
    // Antiquité
    {
      period_id: getPeriodId('antiquite'),
      title: 'Fondation de Rome',
      slug: 'fondation-de-rome',
      description: 'Selon la tradition, Rome est fondée par Romulus en 753 av. J.-C. sur la colline du Palatin.',
      detailed_content: 'La fondation de Rome mêle mythe et histoire. Selon la légende, Romulus et Rémus, fils du dieu Mars et de la vestale Rhéa Silvia, sont élevés par une louve. Romulus tue son frère et fonde la ville. Archéologiquement, des traces d\'occupation remontent au Xe siècle av. J.-C.',
      date_display: '753 av. J.-C.',
      year: -753,
      location: 'Rome, Italie',
      latitude: 41.9028,
      longitude: 12.4964,
      importance: 5,
      category: 'politique',
    },
    {
      period_id: getPeriodId('antiquite'),
      title: 'Bataille de Marathon',
      slug: 'bataille-de-marathon',
      description: 'Victoire des Grecs sur les Perses en 490 av. J.-C., symbole de la résistance de la démocratie.',
      date_display: '490 av. J.-C.',
      year: -490,
      location: 'Marathon, Grèce',
      latitude: 38.1535,
      longitude: 23.9583,
      importance: 4,
      category: 'militaire',
    },
    {
      period_id: getPeriodId('antiquite'),
      title: 'Mort d\'Alexandre le Grand',
      slug: 'mort-alexandre-le-grand',
      description: 'Alexandre le Grand meurt à Babylone en 323 av. J.-C., laissant un empire s\'étendant de la Grèce à l\'Inde.',
      date_display: '323 av. J.-C.',
      year: -323,
      location: 'Babylone, Irak actuel',
      importance: 5,
      category: 'politique',
    },
    {
      period_id: getPeriodId('antiquite'),
      title: 'Chute de l\'Empire romain d\'Occident',
      slug: 'chute-empire-romain-occident',
      description: 'En 476, le dernier empereur romain d\'Occident, Romulus Augustule, est déposé par Odoacre.',
      detailed_content: 'La chute de l\'Empire romain d\'Occident en 476 marque traditionnellement la fin de l\'Antiquité et le début du Moyen Âge. Les invasions barbares, la crise économique et l\'affaiblissement de l\'armée contribuent à la dislocation de l\'empire.',
      date_display: '4 septembre 476',
      year: 476,
      month: 9,
      day: 4,
      location: 'Ravenne, Italie',
      importance: 5,
      category: 'politique',
    },

    // Moyen Âge
    {
      period_id: getPeriodId('moyen-age'),
      title: 'Baptême de Clovis',
      slug: 'bapteme-de-clovis',
      description: 'Clovis, roi des Francs, se fait baptiser à Reims vers 496, scellant l\'alliance entre la monarchie et l\'Église.',
      date_display: 'Vers 496',
      year: 496,
      location: 'Reims, France',
      latitude: 49.2583,
      longitude: 3.5233,
      importance: 4,
      category: 'religion',
    },
    {
      period_id: getPeriodId('moyen-age'),
      title: 'Sacre de Charlemagne',
      slug: 'sacre-de-charlemagne',
      description: 'Charlemagne est sacré empereur par le pape Léon III le 25 décembre 800 à Rome.',
      date_display: '25 décembre 800',
      year: 800,
      month: 12,
      day: 25,
      location: 'Rome, Italie',
      latitude: 41.9022,
      longitude: 12.4539,
      importance: 5,
      category: 'politique',
    },
    {
      period_id: getPeriodId('moyen-age'),
      title: 'Prise de Constantinople',
      slug: 'prise-de-constantinople-1453',
      description: 'Les Ottomans de Mehmed II s\'emparent de Constantinople le 29 mai 1453, mettant fin à l\'Empire byzantin.',
      date_display: '29 mai 1453',
      year: 1453,
      month: 5,
      day: 29,
      location: 'Constantinople (Istanbul), Turquie',
      latitude: 41.0082,
      longitude: 28.9784,
      importance: 5,
      category: 'militaire',
    },

    // Renaissance
    {
      period_id: getPeriodId('renaissance'),
      title: 'Découverte de l\'Amérique',
      slug: 'decouverte-amerique',
      description: 'Christophe Colomb atteint les Amériques le 12 octobre 1492, ouvrant l\'ère des grandes découvertes.',
      date_display: '12 octobre 1492',
      year: 1492,
      month: 10,
      day: 12,
      location: 'San Salvador, Bahamas',
      importance: 5,
      category: 'exploration',
    },
    {
      period_id: getPeriodId('renaissance'),
      title: 'Édit de Nantes',
      slug: 'edit-de-nantes',
      description: 'Henri IV promulgue l\'édit de Nantes en 1598, accordant la liberté de culte aux protestants et mettant fin aux guerres de Religion.',
      date_display: '30 avril 1598',
      year: 1598,
      month: 4,
      day: 30,
      location: 'Nantes, France',
      latitude: 47.2184,
      longitude: -1.5536,
      importance: 4,
      category: 'politique',
    },

    // Temps modernes
    {
      period_id: getPeriodId('temps-modernes'),
      title: 'Déclaration d\'indépendance américaine',
      slug: 'declaration-independance-americaine',
      description: 'Les treize colonies britanniques d\'Amérique déclarent leur indépendance le 4 juillet 1776.',
      date_display: '4 juillet 1776',
      year: 1776,
      month: 7,
      day: 4,
      location: 'Philadelphie, États-Unis',
      latitude: 39.9526,
      longitude: -75.1652,
      importance: 5,
      category: 'politique',
    },

    // Époque contemporaine
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Prise de la Bastille',
      slug: 'prise-de-la-bastille',
      description: 'Le peuple de Paris s\'empare de la Bastille le 14 juillet 1789, symbole du début de la Révolution française.',
      date_display: '14 juillet 1789',
      year: 1789,
      month: 7,
      day: 14,
      location: 'Paris, France',
      latitude: 48.8532,
      longitude: 2.3692,
      importance: 5,
      category: 'politique',
    },
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Bataille de Waterloo',
      slug: 'bataille-de-waterloo',
      description: 'Défaite finale de Napoléon le 18 juin 1815, qui met fin à l\'Empire et redessine la carte de l\'Europe.',
      date_display: '18 juin 1815',
      year: 1815,
      month: 6,
      day: 18,
      location: 'Waterloo, Belgique',
      latitude: 50.7140,
      longitude: 4.4119,
      importance: 5,
      category: 'militaire',
    },
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Abolition de l\'esclavage en France',
      slug: 'abolition-esclavage-france',
      description: 'La France abolit définitivement l\'esclavage le 27 avril 1848, sous l\'impulsion de Victor Schœlcher.',
      date_display: '27 avril 1848',
      year: 1848,
      month: 4,
      day: 27,
      location: 'Paris, France',
      importance: 5,
      category: 'société',
    },
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Armistice du 11 novembre 1918',
      slug: 'armistice-11-novembre-1918',
      description: 'L\'armistice signé le 11 novembre 1918 met fin à la Première Guerre mondiale.',
      date_display: '11 novembre 1918',
      year: 1918,
      month: 11,
      day: 11,
      location: 'Rethondes, France',
      latitude: 49.4267,
      longitude: 2.9372,
      importance: 5,
      category: 'militaire',
    },
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Débarquement de Normandie',
      slug: 'debarquement-normandie',
      description: 'Le 6 juin 1944 (Jour J), les forces alliées débarquent en Normandie, marquant le début de la libération de l\'Europe.',
      date_display: '6 juin 1944',
      year: 1944,
      month: 6,
      day: 6,
      location: 'Normandie, France',
      latitude: 49.3433,
      longitude: -0.8683,
      importance: 5,
      category: 'militaire',
    },
    {
      period_id: getPeriodId('epoque-contemporaine'),
      title: 'Chute du mur de Berlin',
      slug: 'chute-mur-berlin',
      description: 'Le 9 novembre 1989, le mur de Berlin tombe, symbolisant la fin de la Guerre froide.',
      date_display: '9 novembre 1989',
      year: 1989,
      month: 11,
      day: 9,
      location: 'Berlin, Allemagne',
      latitude: 52.5163,
      longitude: 13.3777,
      importance: 5,
      category: 'politique',
    },
  ]);

  // Wars
  await knex('wars').insert([
    {
      name: 'Guerre de Cent Ans',
      slug: 'guerre-de-cent-ans',
      description: 'Conflit entre les royaumes de France et d\'Angleterre, ponctué de trêves, de 1337 à 1453.',
      detailed_content: 'La guerre de Cent Ans oppose les Plantagenêts aux Valois pour la couronne de France. Elle voit l\'émergence de Jeanne d\'Arc qui libère Orléans en 1429. Le conflit se termine par la victoire française à la bataille de Castillon (1453).',
      year_start: 1337,
      year_end: 1453,
      location: 'France, Angleterre',
      belligerents: JSON.stringify({ camp1: ['Royaume de France'], camp2: ['Royaume d\'Angleterre'] }),
      casualties_estimate: 'Plusieurs millions (combats, famines, épidémies)',
      outcome: 'Victoire française',
      consequences: 'Affirmation de la nation française, fin de la présence anglaise en France (sauf Calais), renforcement du pouvoir royal.',
    },
    {
      name: 'Première Guerre mondiale',
      slug: 'premiere-guerre-mondiale',
      description: 'Conflit mondial de 1914 à 1918 opposant les Alliés aux Empires centraux.',
      detailed_content: 'Déclenchée par l\'assassinat de l\'archiduc François-Ferdinand à Sarajevo, la Grande Guerre mobilise plus de 70 millions de soldats. La guerre des tranchées sur le front ouest cause des pertes considérables. L\'entrée en guerre des États-Unis en 1917 contribue à la victoire des Alliés.',
      year_start: 1914,
      year_end: 1918,
      location: 'Europe, Moyen-Orient, Afrique',
      belligerents: JSON.stringify({ camp1: ['France', 'Royaume-Uni', 'Russie', 'Italie', 'États-Unis'], camp2: ['Allemagne', 'Autriche-Hongrie', 'Empire ottoman'] }),
      casualties_estimate: '18,6 millions de morts (militaires et civils)',
      outcome: 'Victoire des Alliés',
      consequences: 'Traité de Versailles, disparition des empires centraux, création de la Société des Nations, redécoupage des frontières européennes.',
    },
    {
      name: 'Seconde Guerre mondiale',
      slug: 'seconde-guerre-mondiale',
      description: 'Conflit planétaire de 1939 à 1945, le plus meurtrier de l\'histoire.',
      detailed_content: 'La Seconde Guerre mondiale est déclenchée par l\'invasion de la Pologne par l\'Allemagne nazie. Le conflit s\'étend à tous les continents. La France est occupée de 1940 à 1944. La Résistance et les forces de la France libre luttent pour la libération. Le conflit se termine par la capitulation allemande (8 mai 1945) et japonaise (2 septembre 1945).',
      year_start: 1939,
      year_end: 1945,
      location: 'Monde entier',
      belligerents: JSON.stringify({ camp1: ['France', 'Royaume-Uni', 'URSS', 'États-Unis', 'Chine'], camp2: ['Allemagne nazie', 'Italie fasciste', 'Japon impérial'] }),
      casualties_estimate: '70 à 85 millions de morts',
      outcome: 'Victoire des Alliés',
      consequences: 'Création de l\'ONU, début de la Guerre froide, décolonisation, construction européenne, procès de Nuremberg.',
    },
  ]);
}
